### ISSUE TITLE
unable to install ipkernel with the latest version of python 3.11.0

### ISSUE THREAD

**Issue by Defcon404** [ipython/ipykernel#1011]
Please provide support for Python 3.11.0.
I tried running Jupiter notebook via Vs code with ipkernel bun unable to do so because the latest version of ipkernel does not 
support the latest version of python 3.11.0.
Kindly please provide official support for this version of python as well.

Thank You

**Comment by blink1073** [comment]
Hi @Defcon404, we are testing against Python 3.11 in GitHub Actions, and our released files are not Python version-specific.   Can you describe the error you are seeing?

**Comment by Defcon404** [comment]
@blink1073 
Hello,
Kindly please check this for detailed information related to the error.
https://github.com/microsoft/vscode-jupyter/issues/11820

**Comment by Defcon404** [comment]
@blink1073 
When i try to run the notebook cell i get the following error (shown in jpg named error1)
and when I follow the message and try to run the command in cmd as admin I get the following error (shown in jpg named error2)
![error1](https://user-images.githubusercontent.com/83384787/199139369-0ca82154-f308-458c-b95c-faa631f8c8a0.jpg)
![error2](https://user-images.githubusercontent.com/83384787/199139373-8465e327-9f43-44ae-8be4-4507b6317f0f.jpg)

**Comment by Carreau** [comment]
Thanks for your report. 

When possible, please take the time to provide the full error messages. Here we see only the last few lines. And if possible, provide them as text so we can copy/past, and not have to retype. 

Also please avoid pinging specific people unless critical, we have 100ds of notification s a day. And this is a new Python that was release less than 2 weeks aog, so errors are expected. 

The screenshot seem to state 'Failed to build psutils', so please try to install psutils separately to see if it works. IF you can't get psutil to install, then it is a psutil issue. 

I'm closing here as I'm quite sure this is a psutil problem, but we can reopen if necessary.

**Comment by blink1073** [comment]
Yes, Open Source Software is a highly interdependent system, mostly built by volunteers.  ipykernel depends on psutil, which has not yet had a chance to build a wheel for Python 3.11.
