### ISSUE TITLE
Recommended way to detect interactive terminal?

### ISSUE THREAD

**Issue by hugovk** [ipython/ipykernel#1024]
I'm maintaining the [termcolor](https://github.com/termcolor/termcolor) colour library and [recently added tty detection](https://github.com/termcolor/termcolor/pull/25), so colour is disabled for things like pipes:

```python
def _can_do_colour() -> bool:
    """Check env vars and for tty/dumb terminal"""
    if "ANSI_COLORS_DISABLED" in os.environ:
        return False
    if "NO_COLOR" in os.environ:
        return False
    if "FORCE_COLOR" in os.environ:
        return True
    return (
        hasattr(sys.stdout, "isatty")
        and sys.stdout.isatty()
        and os.environ.get("TERM") != "dumb"
    )
```

https://github.com/termcolor/termcolor/blob/ec269e608a08b33beb739b6ab5f17b9217a5692a/src/termcolor/termcolor.py#L106-L118

Unfortunately this means colour is disabled in Jupyter/JupyterLab: https://github.com/termcolor/termcolor/issues/28

I see there was a plan to set `isatty` to `True` for `ipykernel.iostream.OutStream`, but instead it was made configurable to make sure things like pagers (less, more) didn't get confused:

* https://github.com/ipython/ipykernel/pull/683
* https://github.com/ipython/ipykernel/pull/683#issuecomment-855950592

So at the moment, if a Jupyter user wants colour from termcolor, they need to either set an env var `FORCE_COLOR=1`, or configure `ipykernel.iostream.OutStream` so `isatty=True`.

But if we wanted to add auto-detection to termcolor's `_can_do_colour`, what sort of thing should we query to know Jupyter is being used in an interactive way?

Thank you!

**Comment by blink1073** [comment]
Hi @hugovk, we inject some environment variables [here](https://github.com/ipython/ipykernel/blob/6607b9d2edf37cc5731b4709e1ccdad5d6132a5d/ipykernel/zmqshell.py#L479), we could add an environment variable that you could put in your `_can_do_color` test, or perhaps set `FORCE_COLOR=1` if that makes more sense.

**Comment by hugovk** [comment]
An env var would be great.

Or setting `FORCE_COLOR=1` is an interesting idea, it's also supported by a number of other tools, such as Rich, pytest, nox, tox, pypa/build (see links in https://github.com/Textualize/rich/issues/2425).

Having said that, I see you're already setting `env["CLICOLOR"] = "1"` there, so I should probably add support for that into termcolor:

* https://bixense.com/clicolors/

**Comment by blink1073** [comment]
Based on that link, it seems like `CLICOLOR_FORCE` is what we should be using, since we are not a tty.

**Comment by blink1073** [comment]
But we could set both since `rich` already expects `CLICOLOR`.
