### ISSUE TITLE
Duplicate function `find_connection_file` with similar API to one in `jupyter_client`

### ISSUE THREAD

**Issue by jakirkham** [ipython/ipykernel#103]
From Gitter [October 21, 2015 5:11 PM](https://gitter.im/jupyter/jupyter?at=5627ff8948fc9e2d6fe877bf):

> So, I was using `find_connection_file` from `jupyter_client.connect`. It turns out there is another implementation under `ipykernel.connect`, which does work. Is there a reason for two different implementations of this function?

Seems like there are two copies of the same function, but they act differently.

If this is intentional, it may be worth finding a different name to highlight the differences and deprecate the old one. If they are meant to behave more similarly, then a bug fix is in order and some discussion should occur about which one to deprecate, if possible, and why.

Related: https://github.com/jupyter/jupyter_client/issues/85

**Comment by Carreau** [comment]
I think the  ipykernel one might have a (slightly) different behavior for historical reasons (it will look in `.ipython`). You can see that as the the ipykernel does even call the jupyter_client one at the end. 

I don't see any obvious reason not to deprecate it slowly, or at least warn not to use it. 
I doubt we can completely remove it, but it can likely become a private method at some point.

**Comment by minrk** [comment]
Yeah, I think it is only slightly different in the path it uses. It's a good idea for one or the other to get a new name, just so it's clearer when one is used instead of the other (I can almost guarantee that in doing so we will find at least one case where we are using the wrong one).

**Comment by minrk** [comment]
Actually, turns out we don't really use this one for anything. We can just deprecate it.
