### ISSUE TITLE
Latest version break IPyWidgets

### ISSUE THREAD

**Issue by DonJayamanne** [ipython/ipykernel#1043]
IPyKernel Version: 6.18.3
Install Jupyter and ipywidgets 
Run a notebook with the following code
* Cell 1
```python
from ipywidgets import FloatSlider, IntSlider, Image, IntText, link

slider = IntSlider(description="Continuous Slider", continuous_update=True)
textbox = IntText(description="Continuous Text", continuous_update=True)

link((slider, 'value'), (textbox, 'value'))
```
* Cell 2
```
slider
```
* Cell 3
```
textbox
```

Drag the slider and the value in the textbox should change

Now: Install ipykernel==6.17.1 (previous version)
Test the same code and the value in the textbox will end up getting updated.

**Comment by blink1073** [comment]
Yanked.  @martinRenou I'm inclined to completely back out these comm changes, I don't know how we can do this in a backward-compatible way.

**Comment by DonJayamanne** [comment]
Since that version has been pull out, please feel free to close this issue.
I'd close it, though I'm unsure whether you'd use this to track some breakage in that version/main branch before pushing the next version

**Comment by blink1073** [comment]
Thanks @DonJayamanne, let's leave this open for discussion.

**Comment by maartenbreddels** [comment]
Let me take a look if I can add a test case that covers this, @blink1073 you didn't expose this in the test of #1048 yet right?
