### ISSUE TITLE
Can't update `children` trait after widget is displayed.

### ISSUE THREAD

**Issue by bollwyvl** [ipython/ipykernel#1060]
Akin to #1059, here's another [fun gist with binder](https://gist.github.com/bollwyvl/181eed3cda265e205310f829aa7cc600) that demonstrates some issues observed while try to upgrade to `6.19.x`.

Basically:
- Creating a `HBox` with `children` displays them immediately
- Creating an `HBox` and then setting `children` doesn't show anything at all
  - well, the `.widget-hbox` gets created, but its empty, and never updates

Again, I'll do a bit more debugging.

![Screenshot from 2022-12-19 17-01-17](https://user-images.githubusercontent.com/45380/208544224-ac8b456f-0d37-46e8-9306-726e2dfb2962.png)

**Comment by bollwyvl** [comment]
I've added kernelspy to the gist.

| 6.17 | 6.19 |
|- | - |
| ![image](https://user-images.githubusercontent.com/45380/208549438-beda61a7-2c86-4346-aff8-252281766876.png) | ![image](https://user-images.githubusercontent.com/45380/208549323-59d1c02a-10d8-4915-a5a2-58b55ca9952a.png)

**Comment by bollwyvl** [comment]
Here's the expanded `comm_msg` missing in in 6.19: sure enough, it's the one that sets the children.

![image](https://user-images.githubusercontent.com/45380/208549751-e277dbc1-5363-4fa4-b222-b7d05756539a.png)

**Comment by bollwyvl** [comment]
In `notify_change`, `ipywidgets` checks if the `comm.kernel` is `None`, this appears to always be the case, even for previously-established comms.

https://github.com/jupyter-widgets/ipywidgets/blob/f89c5d983d534fe3bbf8440f085e228ee89d681c/python/ipywidgets/ipywidgets/widgets/widget.py#L689

**Comment by maartenbreddels** [comment]
Ok, this was the bug I was hunting, didn't expect this. Thanks again 🙏

**Comment by bollwyvl** [comment]
This was a good exercise: i guess my lesson learned was that going right to the message trace its where it's at for these things.

kernelspy is fine, and but not very fine-grained, and running the full lab UI requires so many downstreams that it might be limiting. 

Perhaps something lower level that allowed for capturing full traces as JSON lines would be a good feature... building it into the kernel itself would be... something, but probably makes more sense to do it out-of-band so that you can run it against other kernels, akin to [jupyter_kernel_test](https://github.com/jupyter/jupyter_kernel_test), but maybe something that worked with an existing forensic tool, e.g. `kernelshark` for `wireshark`.
