### ISSUE TITLE
Traceback friendly frame name "In [1]"

### ISSUE THREAD

**Issue by Tronic** [ipython/ipykernel#1087]
I am working on a HTML traceback formatter https://github.com/sanic-org/tracerite that was originally written years ago for Jupyter Notebooks, and I am trying to bring it up to date.

Frames' `co_filename` used to be something like `<ipython-input-2-0a3987b48b2a>` from here one could extract the frame number (2) for `In [2]`, and it still is so in plain IPython, but all Notebooks instead give an actual filename.

My question concerns on where to either find this information now, or alternatively in which project/module the standard traceback formatting code might exist so that I could look at it for how they do it, because they certainly still show the friendly names.

Sorry to post this as an issue, as I've found no other means of reaching relevant developers, since despite it being a regression towards this project that something somewhere changed, I don't think it is a bug per se. Related to #1075 but that part is working for me now.

**Comment by martinRenou** [comment]
> My question concerns on where to either find this information now, or alternatively in which project/module the standard traceback formatting code might exist so that I could look at it for how they do it, because they certainly still show the friendly names.

This is done in IPython, it was implemented in https://github.com/ipython/ipython/pull/13043

Every cell execution uses an in-memory "file" that is used by this traceback formatting and by the JupyterLab debugger for breakpoints tracking.

**Comment by Tronic** [comment]
Thanks, that was extremely helpful. Now it works perfectly again :)
