### ISSUE TITLE
ipywidgets expects Comm, not BaseComm

### ISSUE THREAD

**Issue by matthewturk** [ipython/ipykernel#1090]
Hi!  I've been trying to track down an issue with my usage of `ipywidgets`, described [on discourse](https://discourse.jupyter.org/t/trouble-creating-a-widget-in-kernel-from-frontend/17887).  The basic gist is:

 - I'm attempting to create a widget from the client by using a `model.widget_manager`'s method `new_widget`.  In previous versions, this worked, but now, it doesn't.
 - The issue seems to stem from the kernel attempting to create a new comm instance for a widget, but supplying to that widget a `BaseComm` rather than a `Comm`, which throws a validation error.

After digging through this, it looks to me like `ipywidgets` declares `comm = Instance('ipykernel.comm.Comm', allow_none=True)`, but `ipykernel.ipkernel.create_comm` explicitly creates a `BaseComm`, so the traitlet doesn't validate, and the comm fails to properly initialize.  This results in the widgets not being synced back to the kernel from the frontend.

I confess that while I've spent time going through the code, I'm not entirely sure if this could potentially be a version mismatch, or if this is an oversight for a use case that may not come up terribly frequently.

My versions:

 - `ipywidgets` - 8.0.4
 - `ipykernel` - 6.21.1
 - `comm` - 0.1.2

I was able to address the problem I was having by changing the import and usage of `BaseComm` to `Comm` in `ipkernel.py`, and so if this is an acceptable solution I'd be happy to issue a pull request.  (My hesitance is that there may be unexpected downstream effects of a change to something so deep in the kernel code, and so I wanted to open the issue as possible first step.)

**Comment by blink1073** [comment]
Hi @matthewturk, please do open a PR.  We test most known downstream consumers in `Jupyter` and `spyder`, seeing if those downstream tests fail would be a good indicator.

**Comment by maartenbreddels** [comment]
I think this is an ipywidget issue.

@matthewturk In https://github.com/jupyter-widgets/ipywidgets/pull/3602#issuecomment-1422851291 I removed the comm being an Instance of this class. I think this will fix it, but we never merged it.

**Comment by matthewturk** [comment]
@maartenbreddels That PR is pretty big though -- does it need to be a part of that, or would a smaller PR that simply loosened restrictions work, so that we don't have to pin all our dependencies to a lower version?

**Comment by maartenbreddels** [comment]
I think if we just cherry-pick, https://github.com/jupyter-widgets/ipywidgets/pull/3602/commits/c1c34f9010b40ac3374ae0c6383f64a992207ca7 we should be able to get this in sooner.

An even saver option, it to change it to `traitlets.Any`. I don't think we need the type safety for the comm.

**Comment by martinRenou** [comment]
I will work on finishing https://github.com/jupyter-widgets/ipywidgets/pull/3533 this morning. This PR uses `traitlets.Any` and we should backport it to ipywidgets 7

**Comment by maartenbreddels** [comment]
I think we should backport this indeed
