### ISSUE TITLE
__session__ picks up new name of a notebook only through specific kernel restarts

### ISSUE THREAD

**Issue by suganya-sk** [ipython/ipykernel#1102]
From https://github.com/Quansight/deshaw/issues/167#issuecomment-1420479621, about the `__session__` global variable,

> That may not yet reflect renames of the file until kernel restart.

On renaming a notebook, the new name is reflected in `__session__` when the kernel is started by choosing the same kernel in Kernel -> Change Kernel or Switch Kernel menus. However, the new name is not picked up when kernel is restarted using any of the Kernel -> Restart Kernel ... options. 

Is this difference expected?

**Comment by Carreau** [comment]
I'll investigate. It might be an issue on the Jupyter Server side.

**Comment by divyansshhh** [comment]
Hi, I'm still able to reproduce this. Any updates here?

**Comment by Carreau** [comment]
I was not able to narrow down or properly reproduce, I'll retry on more recent versions.

**Comment by Carreau** [comment]
I see where this is coming from. It is fixable but it might take while, time to propagate the API changes while keeping backward compatibility. 

One way to force `__session__` to update is to change kernel twice. Say from KernelA to KernelB, and then back to A. 

So reasons related to efficiency and scheduling in cluster the environment of a Kernel is not recomputed on simple restart.

**Comment by Carreau** [comment]
This now should be fixed if you have the latest Jupyter_client (8.6), and Jupyter_server (2.10)
