### ISSUE TITLE
6.27.0 broke the `%edit` magic

### ISSUE THREAD

**Issue by ccordoba12** [ipython/ipykernel#1170]
- We have a test for that magic in Spyder and it started to fail with 6.27.0.
- I checked locally and can confirm that that's the case: the magic works well in 6.26.0 but fails in 6.27.0
- My guess is that the problem was introduced by the changes done in PR #1169.

@blink1073, could you take a look at this one? I'd love to help but unfortunately I don't have time to do it right now.

**Comment by blink1073** [comment]
I've yanked the 6.27.0 release, I'll see about adding tests for some magics before releasing again.

**Comment by blink1073** [comment]
Can you point me to your existing tests?

**Comment by ccordoba12** [comment]
It's this one:

https://github.com/spyder-ide/spyder/blob/06a148be300ca830fa74b69c20105cd8f72a3c72/spyder/app/tests/test_mainwindow.py#L84

What we do is testing that running `%edit foo.py` in the console opens `foo.py` in our editor. I don't know how to test that only in the kernel.

**Comment by blink1073** [comment]
This was actually the offending [change](https://github.com/ipython/ipykernel/pull/1167/files#diff-7aa1308f4e4755b2ac385952302d9bbe3784d4474d8d23a4b083d6853c8b0357R305), from my linting PR. `Path` vs `str`, tricky...
