### ISSUE TITLE
Can not install ipykernel

### ISSUE THREAD

**Issue by xfzhang990** [ipython/ipykernel#1192]
Hi!

My jupyterlab has python version 3.8.19, but I need python version >=3.9 to be able to install package instructor. So I want to change the python version to 3.11.7 in Jupyterlab.

In the command line, I input:
pip install ipykernel

Then it comes the following:
C:\Users\xiaofen.zhang>pip install ipykernel
Collecting ipykernel
  Using cached ipykernel-6.28.0-py3-none-any.whl.metadata (6.0 kB)
Collecting comm>=0.1.1 (from ipykernel)
  Using cached comm-0.2.1-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\xiaofen.zhang\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ipykernel) (1.8.0)
Collecting ipython>=7.23.1 (from ipykernel)
  Using cached ipython-8.20.0-py3-none-any.whl.metadata (5.9 kB)
Collecting jupyter-client>=6.1.12 (from ipykernel)
  Using cached jupyter_client-8.6.0-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\xiaofen.zhang\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ipykernel) (5.7.1)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\xiaofen.zhang\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ipykernel) (0.1.6)
Requirement already satisfied: nest-asyncio in c:\users\xiaofen.zhang\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ipykernel) (1.5.8)
Requirement already satisfied: packaging in c:\users\xiaofen.zhang\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ipykernel) (23.2)
Requirement already satisfied: psutil in c:\users\xiaofen.zhang\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ipykernel) (5.9.7)
Requirement already satisfied: pyzmq>=24 in c:\users\xiaofen.zhang\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ipykernel) (25.1.2)
Requirement already satisfied: tornado>=6.1 in c:\users\xiaofen.zhang\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ipykernel) (6.4)
Requirement already satisfied: traitlets>=5.4.0 in c:\users\xiaofen.zhang\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ipykernel) (5.14.1)
Requirement already satisfied: decorator in c:\users\xiaofen.zhang\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ipython>=7.23.1->ipykernel) (5.1.1)
Collecting jedi>=0.16 (from ipython>=7.23.1->ipykernel)
  Using cached jedi-0.19.1-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\users\xiaofen.zhang\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ipython>=7.23.1->ipykernel) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\users\xiaofen.zhang\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ipython>=7.23.1->ipykernel) (2.17.2)
Collecting stack-data (from ipython>=7.23.1->ipykernel)
  Using cached stack_data-0.6.3-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: colorama in c:\users\xiaofen.zhang\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ipython>=7.23.1->ipykernel) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\xiaofen.zhang\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from jupyter-client>=6.1.12->ipykernel) (2.8.2)
Requirement already satisfied: platformdirs>=2.5 in c:\users\xiaofen.zhang\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel) (4.1.0)
Requirement already satisfied: pywin32>=300 in c:\users\xiaofen.zhang\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel) (306)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\users\xiaofen.zhang\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel) (0.8.3)
Requirement already satisfied: wcwidth in c:\users\xiaofen.zhang\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel) (0.2.13)
Requirement already satisfied: six>=1.5 in c:\users\xiaofen.zhang\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.8.2->jupyter-client>=6.1.12->ipykernel) (1.16.0)
Requirement already satisfied: executing>=1.2.0 in c:\users\xiaofen.zhang\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from stack-data->ipython>=7.23.1->ipykernel) (2.0.1)
Collecting asttokens>=2.1.0 (from stack-data->ipython>=7.23.1->ipykernel)
  Using cached asttokens-2.4.1-py2.py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: pure-eval in c:\users\xiaofen.zhang\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from stack-data->ipython>=7.23.1->ipykernel) (0.2.2)
Using cached ipykernel-6.28.0-py3-none-any.whl (114 kB)
Using cached comm-0.2.1-py3-none-any.whl (7.2 kB)
Using cached ipython-8.20.0-py3-none-any.whl (809 kB)
Using cached jupyter_client-8.6.0-py3-none-any.whl (105 kB)
Using cached jedi-0.19.1-py2.py3-none-any.whl (1.6 MB)
Using cached stack_data-0.6.3-py3-none-any.whl (24 kB)
Using cached asttokens-2.4.1-py2.py3-none-any.whl (27 kB)
Installing collected packages: jedi, comm, asttokens, stack-data, jupyter-client, ipython, ipykernel
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\xiaofen.zhang\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\jedi\\third_party\\django-stubs\\django-stubs\\contrib\\contenttypes\\management\\commands\\remove_stale_contenttypes.pyi'

How to solve this issue? Thanks!

**Comment by minrk** [comment]
This is not an ipykernel issue, but rather a general installation issue. It looks like you might be hitting [this issue](https://stackoverflow.com/questions/63587626/unable-to-install-jupyter-notebook), in which case you may need t "enable long path" support on your system. Or create an environment in a directory with a shorter prefix.

**Comment by xfzhang990** [comment]
Hi @minrk Thanks for the answer. I think you are right, there is limitation with long path.
