### ISSUE TITLE
Incorrect version string on main

### ISSUE THREAD

**Issue by mlucool** [ipython/ipykernel#1240]
When I installed from main, I found it confusing that https://github.com/ipython/ipykernel/blob/main/ipykernel/_version.py#L8 still has 6.23.3 both because 6.23.4 was released, and main I believe should be considered a major breaking version (so I would have expected 7.0.0 or something like that). Happy to make a PR - but was unsure what people wanted here.

Feel free to close if you prefer not to update right now.

**Comment by davidbrochart** [comment]
Yes, it can be updated to `7.0.0`. Feel free to make a PR, thanks!
