### ISSUE TITLE
[IPKernelApp] ERROR | No such comm target registered: ipython.widget

### ISSUE THREAD

**Issue by Dom-nik** [ipython/ipykernel#132]
When trying to use ipykernel to run Python 2 in JupyterHub I'm getting this error and some weird behavior: the kernel starts and lets me type whatever I want, but doesn't return anything (neither results, nor errors). Nothing appears in the logs as well.

After some time of the kernel 'running' the following message starts to pop up in the logs in cycles:

> Traceback (most recent call last):
>   File "/usr/local/bin/sudospawner", line 4, in <module>
>     mediator.main()
>   File "/usr/local/lib/python3.3/site-packages/sudospawner/mediator.py", line 138, in main
>     kill(**kwargs)
>   File "/usr/local/lib/python3.3/site-packages/sudospawner/mediator.py", line 54, in kill
>     finish({'alive': alive})
>   File "/usr/local/lib/python3.3/site-packages/sudospawner/mediator.py", line 34, in finish
>     if data and data['ok']:
> KeyError: 'ok'

I'm running JupyterHub 0.6.0 with Jupyter 1.0.0 and ipykernel 4.3.1.
I'm not using anaconda, just plain old python. My kernel.json looks like this (and it points to the right python executable):
```
{
 "display_name": "Python 2", 
 "language": "python", 
 "argv": [
  "/usr/local/bin/python2.7", 
  "-m", 
  "ipykernel", 
  "-f", 
  "{connection_file}"
 ]
}
```

**Comment by minrk** [comment]
This is a recent regression in sudospawner, and should be fixed by jupyterhub/sudospawner#22

**Comment by Dom-nik** [comment]
Thank you for the info! Is there any timeline for this?

BTW. We have the exact same configuration of Jupyterhub with ipykernel (same versions of python packages) running on another box and it works fine. Can you tell me where the difference may be?

**Comment by minrk** [comment]
@Dom-nik I just merged the fix in sudospawner, so it should work now, from master. I will try to do a release soon as well.

**Comment by Dom-nik** [comment]
Thanks, the problem with sudospawner is gone, but the error [`IPKernelApp] ERROR | No such comm target registered: ipython.widget` and weird malfunctioning of ipykernel for python 2 is still there.
