### ISSUE TITLE
Why depend on tornado?

### ISSUE THREAD

**Issue by dimaqq** [ipython/ipykernel#140]
setup.py requires tornado
tornado is never imported
one logger is initialised with name "tornado"

Looks like tornado package is not really needed...

**Comment by minrk** [comment]
tornado provides the eventloop used in the kernel. It ends up being imported by way of zmq, but it is the tornado IOLoop. We could import it directly from tornado to make it clearer.

**Comment by dimaqq** [comment]
I guess pyzmq ought to depend on tornado then, or is that optional because other event loops are possible?
