### ISSUE TITLE
IPython magic UsageErrors do not set status:error on execute_reply

### ISSUE THREAD

**Issue by takluyver** [ipython/ipykernel#143]
And consequently they don't stop execution if you've queued several cells to run. Thanks to @nholtz for reporting this on the mailing list.

**Comment by minrk** [comment]
I *think* this is something to fix in IPython, since that's what's swallowing the UsageError and printing instead of setting an exception state.

**Comment by takluyver** [comment]
Could be either. I was thinking of overriding `show_usage_error()` on the `ZMQInteractiveShell` class here to track the error. This is like what we already do with `_showtraceback()`.

**Comment by minrk** [comment]
We should do away with the `_showtraceback` hack altogether, and get an official mechanism for "this run_cell failed"

**Comment by takluyver** [comment]
`run_cell` returns an `ExecutionResult` instance now, and `result.success` should be a boolean indicating if it succeeded. Hopefully that provides a good way of doing this.

**Comment by takluyver** [comment]
(I'm just having a go at this - I'm pointing this out in case we're duplicating effort right now ;-)
