### ISSUE TITLE
Invalid displayhook for other kernels

### ISSUE THREAD

**Issue by takluyver** [ipython/ipykernel#161]
KernelApp sets `sys.displayhook` to `ZMQDisplayhook`, which sends `execute_result` messages without an execution_count, crashing jupyter_console.

We don't see this in our own code because ZMQInteractiveShell then overrides it with `ZMQShellDisplayHook`, which works correctly. But this is an issue e.g. when running the xonsh kernel.

**Comment by scopatz** [comment]
Thanks for hunting this down!

**Comment by takluyver** [comment]
#162 should fix it.
