### ISSUE TITLE
Unable to setup Python 3.3 conda environment with ipykernel

### ISSUE THREAD

**Issue by par2** [ipython/ipykernel#163]
I'm trying to install `ipykernel` in a Python 3.3 conda environment:

`conda create -n py33 python=3.3 ipykernel`

I get the following conflict:

![image](https://cloud.githubusercontent.com/assets/15694632/17081990/91e13c96-513a-11e6-9dd7-9abe9d77ee13.png)

However, [PyPI says `ipykernel` is compatible with Python 3.3](https://pypi.python.org/pypi/ipykernel/4.3.1).

Can you clarify whether `ipykernel` still supports Python 3.3?  If so, how can I resolve this issue as I would like to set up a py33 kernelspec using `nb_conda_kernels`?

**Comment by takluyver** [comment]
We are still testing on Python 3.3 for the moment, though I don't know how long that will continue. I guess that conda has only built the packages for 3.4 and 3.5; we don't control that process. You should be able to work around it by creating a conda environment without ipykernel and then using pip to install it.

**Comment by par2** [comment]
Thanks
