### ISSUE TITLE
Warning: object.__init__ takes no argument

### ISSUE THREAD

**Issue by rmorshea** [ipython/ipykernel#179]
The following (in 4.3.0) raises a warning:

```
class A(str):

    def __init__(self, *args, **kwargs):
        super(A, self).__init__(*args, **kwargs)

A('asd') # raises warning

# warning = "DeprecationWarning: object.__init__() takes no parameters"
```

Is this accurate? It seems that `str.__init__` is being invoked here, not `object.__init__`.

**Comment by takluyver** [comment]
`str` inherits from `object` (everything does), and presumably it doesn't define its own `__init__` method, so:

```
In [2]: str.__init__ is object.__init__
Out[2]: True
```

Is something in ipykernel triggering this, or is it code that you're running yourself?

**Comment by rmorshea** [comment]
It's from code I'm running myself. I was confused by the fact that running the same code through a console didn't raise a similar warning. I guess that suggests I should be overriding `__new__` rather than `__init__`.

**Comment by takluyver** [comment]
Oh, right. The difference is just because we make DeprecationWarnings visible by default, whereas normally they're not.
