### ISSUE TITLE
How to specify the IP of a kernel from Python? [question] [documentation]

### ISSUE THREAD

**Issue by tiangolo** [ipython/ipykernel#181]
I'm trying to write an ipykernel "launcher" in Python but it's been quite difficult to find out how to use `ipykernel` from inside Python, I can't seem to find enough documentation (I don't know if I'm not looking in the correct place).

Here's what I'm trying to do (it's quite simple).

* Instantiate an IPython Kernel that creates and uses a connection file in a specific place (that seems to be working).
* Make it bind to a specific IP (different than `127.0.0.1`) (I don't know ho to do that).

I know how to achieve all that from the command line using the `ipykernel` command:
```bash
ipykernel --ip=192.168.0.4 -f /tmp/hydrogen/connection.json
```

But I'm not sure what is the way of achieving the same from Python code, I don't find documentation on how to use ipykernel as a module, more complete docstrings or anything.

Up to now, by looking at the code itself of `ipykernel`, I have this:

```python
from ipykernel.kernelapp import IPKernelApp

def main():
    app = IPKernelApp.instance()
    app.connection_file = u'/tmp/hydrogen/connection.json'
    app.initialize()
    app.start()
```

I'm still not sure if that's the correct way of creating an ipykernel instance. I tried updating the `ip` assigning it to `app.ip` (as there seems to be a `self.ip` in the code) but the result is a `False` and the `IP` doesn't change.

--- 

Later I want to use `netifaces` to detect and use an IP in the machine (or Docker container) to connect it remotely (my idea is to use it to easily create kernels for [hydrogen](https://github.com/nteract/hydrogen)).

**Comment by takluyver** [comment]
The IP address is part of the connection file; have you tried setting it to what you want inside the connection file?

Otherwise, I think you need to change it after `app.initialize()`, which will read the connection file.

**Comment by tiangolo** [comment]
Thanks for the reply!

I think that my problem was mainly because I was trying to code using IPython itself as my main interactive Python and that was causing me some issues. ...it's a bit ironic that to build something based on a great tool as IPython I can't use it :smile: 

After trying more (with the pure Python interpreter, etc) it results that changing the attributes of the instance does seem to work (in the pure Python interpreter). And it seemed OK to call `app.initialize()` after that. I didn't have to change the data in the connection file directly.

Here's my simplified final block of code (for that section), in case anyone else tries to do the same:

```python
from ipykernel.kernelapp import IPKernelApp

def main():
    connection_file = u'/tmp/hydrogen/connection.json'
    ip_address = u'192.168.0.4'

    app = IPKernelApp.instance()
    app.connection_file = connection_file
    app.ip = ip_address
    app.initialize()
    app.start()


    ...
```

**Comment by takluyver** [comment]
Aha, yes. Because some of our core classes are singletons, unfortunately there can be some odd effects if you try to run IPython machinery inside IPython. I pushed a while back to try to remove global state, but it's a fairly big task, and there's ~no gain until it's all done.

**Comment by tiangolo** [comment]
Ah, I see. It's OK, I'll just keep using the normal Python for that then. Thanks!
