### ISSUE TITLE
inline figures still use savefig.dpi 

### ISSUE THREAD

**Issue by tkaseman** [ipython/ipykernel#202]
The changelog for ipykernel 4.5.0 says that inline figures now use `figure.dpi` rather than `savefig.dpi`, but I'm still seeing the use of `savefig.dpi`. Is this a bug or am I changing the rcParams incorrectly?

I'm using the Anaconda Python 3 distribution which I  updated to the latest version of all packages earlier this week. The relevant package versions are (from `conda list`):
IPython: 5.1.0
ipykernel: 4.5.0
matplotlib: 1.5.1

What I see when playing with `savefig.dpi`:
![image](https://cloud.githubusercontent.com/assets/15188879/19955848/c7251b08-a1d9-11e6-92e5-c090c3886057.png)

In _ipykernel/pylab/config.py_ I can see that the rc dictionary now uses `figure.dpi` but I haven't been able to track it to where it's used in the figure generation. The code this deep in ipykernel is well beyond my current Python skills.

**Comment by has2k1** [comment]
This issue should be closed. The fix landed in IPython: 5.2.0 (see: ipython/ipython/pull/9868)

**Comment by takluyver** [comment]
Thanks @has2k1 :smiley:
