### ISSUE TITLE
Virtualenvs are no longer detected and automatically used

### ISSUE THREAD

**Issue by ulope** [ipython/ipykernel#206]
The automatic detection and usage of a currently active virtualenv seems to have been broken in the last few releases.

Unfortunately I can't name exact versions since I updated my jupyter/ipykernel a few days ago to the currect versions and only now noticed this.

**Comment by takluyver** [comment]
Sorry, it was deliberately removed in #96. We can't properly use an active virtualenv if IPython is running outside a the env, and we decided that for kernels running inside Jupyter, the attempt to use it was more confusing than useful.

If you want the old behaviour back, you can put the [virtualenv detection code](https://github.com/ipython/ipython/blob/5.1.0/IPython/core/interactiveshell.py#L695) in a startup script.

**Comment by ulope** [comment]
That is really a shame and to be honest I'm quite baffled by this decision. It's not as if you removed the code to reduce maintenance burden (which would be perfectly understandable), but just disabled it in this specific subclass. That seems quite user hostile without a good reason.

**Comment by takluyver** [comment]
Sorry about that. The virtualenv integration was never something we could do perfectly, and it doesn't really fit well with the ability of the notebook frontend to now start multiple different kinds of kernels. The conda people have an integration that lets you pick different environments as kernels; I don't much like that either, but we're continuing to think about how to expose environments in notebooks.

**Comment by ulope** [comment]
Thanks for the response and also I'm sorry if my previous message came off as entitled or too aggressive (it was a bad day). 

I know that maintaining open source software is a difficult task and one usually gets very little recognition for it. So let me thank you very much for making this awesome tool that is ipython, even if I do have a minor quibble on this point :)

**Comment by takluyver** [comment]
Thanks. I've seen much nastier messages around many open source projects, but I don't want IPython & Jupyter to slip into that kind of aggressive communication.
