### ISSUE TITLE
InProcessKernelManager.shutdown_kernel doesn't shut down history saving thread.

### ISSUE THREAD

**Issue by mdickinson** [ipython/ipykernel#214]
The `InProcessKernelManager.shutdown_kernel` method doesn't seem to stop the `IPythonHistorySavingThread` instance associated to the kernel (`kernel_manager.kernel.shell.history_manager`). To avoid having excess threads around when unit-testing, it would be convenient to either have `shutdown_kernel` stop the thread, or to have some other documented API for stopping the history manager.

**Comment by mdickinson** [comment]
This appears to be fixed in ipykernel 4.5.2; thank you! Okay to close?

**Comment by takluyver** [comment]
Thanks
