### ISSUE TITLE
clarification on tornado IOLoop

### ISSUE THREAD

**Issue by Carreau** [ipython/ipykernel#215]
Followup from #141, 

I read the comment on the PR and issue.
AFAIU, we don't need to use the tornado event loop, but we have to when tornado is installed to have compatibility with tornado. Is that right ? Shouldn't that be the responsibility of the ZMQ event loop with the `try/except ImportError/ModuleNotFound` ?

I'm asking because I'm using a 3.6 end (with notebook server on 3.5) and was astonished to see tornado get pulled.

IMHO it seem like tornado should be an optional dependency of ipykernel.

Or did I miss something ?

**Comment by takluyver** [comment]
From #140, it looks like we do depend on using the tornado event loop, which is an optional dependency for pyzmq.

**Comment by Carreau** [comment]
Yes, and it's the _optional_ that disturb me.

I far as I understand:
 - If tornado is installed, we need to use tornado ioloop just _in case_ tornado get imported, or running tornado+zmq does not work.

So we require, import, and use tornado.ioloop.

But, if tornado is not installed, then we do not need to use tornado.ioloop, because we would never need compatibility.

Is that correct ? In which case can we use tornado ioloop only _if_ tornado is installed ?

**Comment by takluyver** [comment]
I think we always use the tornado ioloop to run the kernel, with some extra
bits from pyzmq so it can handle zmq sockets. I may have misremembered
this, but I think tornado is a real dependency of ipykernel (but a soft
dependency of pyzmq).

**Comment by Carreau** [comment]
Ok, fair enough. 
It would be nice to get rid of it. It seem strange to me to require it... but if there are reasons, I'm fine with it.

**Comment by takluyver** [comment]
Well, the kernel needs an event loop, and tornado is one we're familiar
with. Once it requires python 3, we could switch to asyncio, so long as
there's robust zmq support. But as far as I know tornado works well, so why
change?

**Comment by Carreau** [comment]
> Once it requires python 3, we could switch to asyncio, so long as
> there's robust zmq support

Chicken and egg problem, there won't until someone write it, right ?

> But as far as I know tornado works well, so why
> change?

Just having a webserver as a dependency for a kernel seem... strange. 

May I propose for the "transition": use tornato if installed (and require on Py2), and is not install and Py3, fallback on AsyncIO ?

**Comment by minrk** [comment]
I think we should just use tornado and keep it as a simple dependency, like we do now. If someone wants to explore asyncio in the future that's fine, but I don't think there's any downside to using tornado as we do.

**Comment by takluyver** [comment]
I don't really see

**Comment by takluyver** [comment]
I don't see a particular advantage to supporting two event loops at once.
Tornado is not a very heavy dependency.

**Comment by SylvainCorlay** [comment]
Closing this issue as it is mostly a discussion and has been inative for four years.
