### ISSUE TITLE
connect.py imports IPython.paths, should be IPython.utils.path

### ISSUE THREAD

**Issue by marbre** [ipython/ipykernel#22]
I am currently working on ebuilds for the Gentoo-science overlay. Running the tests, I get the following on my system:

```
  File "/tmp/portage/dev-python/ipython-ipykernel-9999/work/ipython-ipykernel-9999/ipykernel/connect.py", line 13, in <module>
    from IPython.paths import get_ipython_dir
ImportError: No module named 'IPython.paths'
```

Following the [documentation](http://ipython.org/ipython-doc/1/api/generated/IPython.utils.path.html#IPython.utils.path.get_ipython_dir), it seems that `IPython.paths` was renamed to `IPython.utils.path`. Replacing it, solves the issue on my system, on which ipython-3.1.0 is installed.

**Comment by takluyver** [comment]
Other way round, parts of IPython.utils.path were moved to `IPython.paths`.

We're splitting up IPython at the moment, so the different pieces, including ipykernel, currently rely on unstable versions of our own packages. You probably want to be packaging the latest stable release, which is IPython 3.1.0. If you want to use versions from Github, you need to get all of our packages, including IPython, from Github.

**Comment by marbre** [comment]
IPython 3.1.0 is already available in the official Gentoo tree. In the science overlay, I am working on Jupyter ebuilds. Thank you for the additional information, in the most Jupyter "subprojects" it says only IPython >= 3.0.0 is required.

**Comment by Carreau** [comment]
Basically we will release all the subproject at the same time with version number 4.0, and they will all require 4.0 of the other subprojects they depends on.  Then it will start to be release at their own pace.
