### ISSUE TITLE
Release 4.6

### ISSUE THREAD

**Issue by minrk** [ipython/ipykernel#235]
We should be about ready to release 4.6, which has some nice fixes and improvements.

- [x] changelog #236
- [x] bump protocol to 5.1 #238
- [x] TextIOBase API #234 
- [x] PID 1 issue affecting docker #233 

cc @JamiesHQ

**Comment by takluyver** [comment]
Is there anything else to do for this? Do you want to push the button?

**Comment by minrk** [comment]
All set, pushing the button now.

**Comment by minrk** [comment]
Released
