### ISSUE TITLE
%gui qt5 no longer works in 4.6.0, while working fine in 4.5.2 in QtConsole

### ISSUE THREAD

**Issue by nanoant** [ipython/ipykernel#240]
It seems that ipykernel 4.6.0 broke Qt5 (non-blocking) event loop integration, so it is not possible to use non-blocking Qt5 UI directly in QtConsole. Following code shows the issue:
```python
%gui qt5
from PyQt5 import QtWidgets
w=QtWidgets.QLabel("Hello world!")
w.show() #<- I can see the label and close the window in 4.5.2, but on 4.6.0 it is frozen
```
Just to be clear, downgrading to 4.5.2 makes `%gui qt5` work as desired again.

**Comment by callegar** [comment]
The popular spyder IDE is broken by the upgrade to ipykernel 4.6.0 and I wonder if this can be the issue.

**Comment by ccordoba12** [comment]
@nanoant, @callegar, what are your Python versions?

**Comment by thomasaarholt** [comment]
Just thought I'd add that qt4 is affected by this as well.

**Comment by callegar** [comment]
@ccordoba12 Working with Python 3.5 (actually 3.5.2), as distributed in Ubuntu 16.10 (yakkety), using qt5, since qt4 cannot be used with spyder due to lack of qtwebkit

**Comment by nanoant** [comment]
@ccordoba12 Python 3.5.3 :: Continuum Analytics, Inc., from MiniConda, running on Windows. Haven't tested on other platforms, though.

**Comment by looooo** [comment]
encountered the same problem (ipykernel4.6, pyside1.2.4, qt4.8.7, python3.5.3 from conda-forge). No interaction between qt-application and jupyter-notebook possible.

**Comment by minrk** [comment]
Should be fixed by #241. I'll try to make a 4.6.1 with this soon.

**Comment by ccordoba12** [comment]
Thanks a lot Min for the quick response!

**Comment by minrk** [comment]
Released 4.6.1

**Comment by callegar** [comment]
That was fast! Thanks! Testing it soon.

**Comment by nanoant** [comment]
@minrk I confirm that 4.6.1 fixes the issue for me as well. Many thanks for such a quick update.
