### ISSUE TITLE
Can no longer specify --Session.key

### ISSUE THREAD

**Issue by andyneff** [ipython/ipykernel#258]
With the new ipykernel in python3, I can no longer use the argument `--Session.key` to set the [session key](https://github.com/jupyter/jupyter_client/blob/086832cc86c92305adeda2f2eb4ea72d43acfb4b/jupyter_client/session.py#L366-L367), as the argument into python is a normal string, and fails to [validate](https://github.com/ipython/traitlets/blob/1ae3c92b8612554bd2ad53aa2af8a624b01014ab/traitlets/traitlets.py#L2094), making it impossible to set the Session key.

Only reproducible in python3

## Test

```
python -m ipykernel --Session.key 044725ee-ede06b25ac55e92a5caaf9eb
```

## Output

```
[IPKernelApp] CRITICAL | Bad config encountered during initialization:
[IPKernelApp] CRITICAL | The 'key' trait of a Session instance must be a bytes object, but a value of 'b044725ee-ede06b25ac55e92a5caaf9eb' <class 'str'> was specified.
```

## Version

```
python -c "import IPython; print(IPython.sys_info())"
{'commit_hash': 'd86648c5d',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/home/me/note2/lib/python3.5/site-packages/IPython',
 'ipython_version': '6.1.0',
 'os_name': 'posix',
 'platform': 'Linux-4.4.0-83-generic-x86_64-with-LinuxMint-18-sarah',
 'sys_executable': '/home/me/note2/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.5.2 (default, Nov 17 2016, 17:05:23) \n[GCC 5.4.0 20160609]'}
```

```
ipykernel==4.6.1
ipython==6.1.0
ipython-genutils==0.2.0
ipywidgets==6.0.0
jupyter-client==5.1.0
jupyter-console==5.1.0
jupyter-contrib-core==0.3.1
jupyter-contrib-nbextensions==0.2.8
jupyter-core==4.3.0
jupyter-highlight-selected-word==0.0.11
jupyter-latex-envs==1.3.8.4
jupyter-nbextensions-configurator==0.2.5
nbconvert==5.2.1
nbformat==4.3.0
notebook==5.0.0
traitlets==4.3.2
```

**Comment by Carreau** [comment]
`python -m ipykernel --help-all` can be of help when you have issues like this. You will after a bit of search find that that the default seem to be `b''`, indeed the key is bytes, and not string, so you need to set bytes, and not strings. Or if you are grep-fluent, select N lines after the key you desire:

```
$ python -m ipykernel --help-all | grep 'Session.key=' -A2
--Session.key=<CBytes>
    Default: b''
    execution key, for signing messages.
```

To pass bytes via the command line, quote your key, and prefix it with `b` : 

```
~/dev/ipykernel/ $ python -m ipykernel --Session.key=b"044725ee-ede06b25ac55e92a5caaf9eb"
NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049

To connect another client to this kernel, use:
    --existing kernel-22705.json
```

TADA™

Depending on your shell you may actually  need the `=` in the command line as well, for the parsing to work correctly (usually it's better to alway leave the `=` when you can, or or you may need an extra  bare ` -- ` to tell python not to swallow arguments.

Does that help ?

**Comment by takluyver** [comment]
I think you need another set of quotes, like this:

```
python3 -m ipykernel --Session.key='b"044725ee-ede06b25ac55e92a5caaf9eb"'
```

**Comment by andyneff** [comment]
Adding the extra b was actually one of the first things I tried, but it was the extra quotes I was missing. Thanks!
