### ISSUE TITLE
Interrupting kernel from notebook closes asyncio event loop

### ISSUE THREAD

**Issue by jbweston** [ipython/ipykernel#263]
The problem can be seen [here](https://nbviewer.jupyter.org/urls/josephweston.org/uploads/asyncio-ipybug.ipynb) running `ipykernel 4.7.0.dev`.

Interrupting the kernel from the notebook closes the `asyncio` event loop, which means that no coroutines can be scheduled on the event loop after this point.

**Comment by basnijholt** [comment]
I'm having the same issue.

If your website ever goes down:
<img width="1165" alt="screen shot 2017-09-01 at 15 57 00" src="https://user-images.githubusercontent.com/6897215/29972966-34f83826-8f2e-11e7-99cc-d102c97598bf.png">
