### ISSUE TITLE
Document how to install kernel for python 2 and 3

### ISSUE THREAD

**Issue by jhamrick** [ipython/ipykernel#27]
This is a pretty frequently asked question -- how to install the python 2 kernel and python 3 kernel simultaneously? The answer is usually "in a virtualenv" but it would be nice to have this documented somewhere with more specific instructions that we can point people to.

**Comment by takluyver** [comment]
Virtualenvs shouldn't be necessary - I install both with `--user`.

I think the important thing to convey is the significance of `ipython kernelspec install`.

**Comment by jhamrick** [comment]
Won't the `ipython` command get overwritten, though? So if you install it with python 2 first and then python 3, you'll end up with `ipython` == `ipython3`, but if you do it the other way around, you'll get `ipython` == `ipython2`? I think that can be unexpected and confusing, which is why I usually install one in a virtualenv.

**Comment by takluyver** [comment]
That's not really related to the kernel, though - we don't use the `ipython` command to launch the kernel.

The command will get overwritten, but I don't think that's a big problem - you'll have `ipython2` and `ipython3` available in any case.

**Comment by jhamrick** [comment]
Yeah, I wasn't totally sure whether to report this here or in the main ipython repo. You don't use the ipython command to launch the kernel, but you *do* use it to install the kernelspec, so I think it's still relevant, at the very least to tell people specifically to use `ipython2` or `ipython3` instead of `ipython`.

I've personally been confused about the ipython command being overwritten, and have had other people be confused by it as well. I think it's kind of cumbersome to have to warn people "make sure you install whichever version of ipython you actually want second, because otherwise it will get overwritten". I would imagine that in most cases the following scenario applies:

1. Person already has ipython installed under e.g. python 3
2. Person wants to install the python 2 kernel as well
3. We tell them, "install ipython with python 2 and then run `ipython kernelspec install`"
4. They get the ipython2 kernel and are happy
5. At some point in the future they want to use ipython from the command line and expect it to be python 3 (since that's what they had before), and are confused when it is not.
6. They need to reinstall ipython with python 3 so that it is the default ipython and are unhappy that things are complicated.

**Comment by jhamrick** [comment]
Also, to clarify, I'm not saying we should try to address the problem of the command getting overwritten, I'm just advocating that they install it in a virtualenv (or at least mention they might want to do that) so they don't encounter the confusion above.

**Comment by minrk** [comment]
Yeah, to that effect, I would probably even recommend people do `/path/to/python -m IPython kernelspec install-self` so that it's really clear which Python is being used. Alternately, it could be:

```
ipython2 kernelspec install-self
ipython3 kernelspec install-self
```

**Comment by takluyver** [comment]
We have [this doc](http://ipython.readthedocs.org/en/latest/install/kernel_install.html) now. It doesn't specifically talk about Python 2 and 3, but:

> if you want to use a kernel with a different version of Python, or in a virtualenv or conda environment

Do we think that's clear enough?

**Comment by jhamrick** [comment]
I don't think it's quite clear enough, but I have some suggestions on how to make it clearer so I'll make some edits and submit a PR.

**Comment by minrk** [comment]
Closed by https://github.com/ipython/ipython/pull/9155
