### ISSUE TITLE
IPykernel 4.7 installs python3 kernelspec on Python 2

### ISSUE THREAD

**Issue by takluyver** [ipython/ipykernel#288]
We've built a universal wheel, so it installs the same `python3` kernelspec regardless of which Python version it's being installed into.

**Comment by blink1073** [comment]
Looks like this repo needs a RELEASE.md. I looked for one when cutting 4.7.

**Comment by blink1073** [comment]
Ah, I see the problem. I have a bash script for releasing python packages that adds the `--universal` switch.   Apologies for that.

**Comment by takluyver** [comment]
No problem. More inspiration for me to work on my release automation tool modeltee ;-)

**Comment by blink1073** [comment]
I don't have a computer with me today.

**Comment by blink1073** [comment]
Modeltee does look promising

**Comment by minrk** [comment]
Yup, should have written that down. I uploaded fixed 4.7.0 py2 and py3 wheels and pulled the universal wheel. We can do a 4.7.1 or 4.7.0post0 if we feel the need to invalidate people's caches.

**Comment by Carreau** [comment]
> Apologies for that.

No problem, we did the same for IPython at some point, and have a big warning in the docs.
One more point for stopping Python 2 support 😆 .

**Comment by takluyver** [comment]
Thanks. I don't think we particularly need a new version, so I'll close this now.

**Comment by blink1073** [comment]
Thanks all!
