### ISSUE TITLE
calling "%matplotlib inline" again resets figure formats

### ISSUE THREAD

**Issue by JanSchulz** [ipython/ipykernel#29]
This should only print a link to the PDF, but actually outputs a png
```
%matplotlib inline
from IPython.display import set_matplotlib_formats
set_matplotlib_formats('pdf')
%matplotlib inline
import matplotlib.pyplot as plt
plt.plot([1,2,3,4,5,6,7,8])
```

This was a bugreport in knitpy (https://github.com/JanSchulz/knitpy/issues/29#issuecomment-120941493), where knitpy calls the first three lines (for PDF output) and a user then added the `%matplotlib inline` call again in a code chunk. From the naming of the argument, I wouldn't have guessed that the image formatter would be touched (at least not again).

**Comment by minrk** [comment]
the enable_matplotlib stage should indeed check if formats have already been set.

**Comment by JanSchulz** [comment]
The solutions seems to involve some kind of way to see whether matplotlib was already enabled and then don't do it again.

* a attribute somewhere, which would indicate that `%matplotlib inline` has already run?
* looking at the formatter and if one of them is already enabled, don't enable it again?

The first "pollutes" a object somewhere, the second is kind of "wrong", if a user uses `%matplotlib inline` and then disables all formats which the call would enable -> the second `%matplotlib inline` would think it wasn't enabled.

**Comment by JanSchulz** [comment]
Any news here? I can do a PR for both ways :-)

**Comment by minrk** [comment]
I would do the first, it seems simplest.

**Comment by JanSchulz** [comment]
PR is in https://github.com/ipython/ipython/pull/8920

**Comment by UramMnisi** [comment]
if using an IDE such as Pycharm, instead of using '%matplotlib inline'. Try using:
(1) 'import matplotlib.pyplot as plt'
(2) plt.imshow(argurment(s))
