### ISSUE TITLE
User warning output.

### ISSUE THREAD

**Issue by Jessime** [ipython/ipykernel#297]
I was messing around with the `warnings` library in a Notebook, and noticed that the output of the warning is different if the warning is not issued from the first line of the function. Here's a demonstration:

![screenshot from 2018-01-16 14-32-13](https://user-images.githubusercontent.com/8493770/35009185-c68ca308-facc-11e7-89ec-a1530138dcc7.png)

As far as I can tell, the second line of the warning comes from [this line](https://github.com/ipython/ipykernel/blob/master/ipykernel_launcher.py#L3). I don't have any sense of what might be going on here, or how to start investigating. So I figured I'd post what I had and see if anyone else has ideas.

```
jessime@jessime-t570:~/Code$ conda list ipykernel
# packages in environment at /home/jessime/anaconda3:
#
ipykernel                 4.6.1            py36hbf841aa_0 
```

**Comment by Jessime** [comment]
Sorry, this is just my misunderstanding `warnings`. I'm going to go ahead and close this issue.

**Comment by takluyver** [comment]
I think it's trying to print the line of code which the warning came from, but getting confused about what the `__main__` module is.
