### ISSUE TITLE
Type annotations in classes inheriting from typing.NamedTuple

### ISSUE THREAD

**Issue by psarka** [ipython/ipykernel#305]
Hi,

Python 3.6 (maybe 3.5 also, not sure), has a nice new syntax to have type annotated named tuples:

```python
from typing import NamedTuple

class Point(NamedTuple):
    x: float
    x: float
```

It would be nice to have this typing information displayed when shift+esc is pressed between the brackets of the initialization statement, as it is when the class is defined in a more usual manner (see the screen shots).

![named_tuple](https://user-images.githubusercontent.com/1212244/35968559-7e8db7b8-0cc4-11e8-82f6-dbbf46657bae.png)
![object_init](https://user-images.githubusercontent.com/1212244/35968563-82b0eae0-0cc4-11e8-862d-676fe9089571.png)

By the way, the type information is available as
```python
Point._field_types  # returns OrderedDict([('x', float), ('y', float)])
```

{'commit_hash': 'ca5443062',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_version': '6.2.1',
 'os_name': 'posix',
 'platform': 'Linux-4.13.0-32-generic-x86_64-with-Ubuntu-17.10-artful',
 'sys_platform': 'linux',
 'sys_version': '3.6.3 (default, Oct  3 2017, 21:45:48) \n[GCC 7.2.0]'}

**Comment by takluyver** [comment]
I think this is up to how Python builds the signature object that we're displaying.

**Comment by psarka** [comment]
You are right. If I tracked it down correctly, ipykernel calls ipython `oinspect`, which in turn calls std lib `inspect`, which gets the signature of `__new__` (named tuple has no `__init__`), which for some reason does not contain the type annotations. Closing this one, will check if I can open a PR in cpython.
