### ISSUE TITLE
Jupyter extension problem with getpass() input in terminal instead of notebook interface

### ISSUE THREAD

**Issue by hellbe** [ipython/ipykernel#308]
Hey,

I'm writing some custom cell magics in an extension which requests input from the user with `input()` and `getpass()` but I am getting a problem with the latter when I load the extension using a startup file. In that case the input question appears in the terminal running the notebook server instead of the notebook web UI.

When I load the extension in the notebook with `%load_ext mymagics` it works fine.

Any clues what it could be? Feels like the startup script is being executed before some hood has been loaded by the kernel?

Thanks,
Simon

**Comment by hellbe** [comment]
To clairfy the load I have created the file `~/.ipython/profile_default/startup/55-mymagics.ipy`

with a single line:
``` 
%load_ext mymagics
```

**Comment by takluyver** [comment]
Are you calling `getpass()` when the startup file runs, or does that define a cell magic which calls `getpass()` later?

Startup files don't really get to interact with the user, so if it needs a password, it should prompt for it the first time the cell magic is run.

**Comment by hellbe** [comment]
@takluyver It's a stateful magic class that is registered and instantiated when loaded from the startup file. Then `getpass()` is called when the first magic cell is executed.

**Comment by takluyver** [comment]
That sounds OK. Can you show the code of the extension?

**Comment by hellbe** [comment]
Here's a slightly stripped down version

__init__.py
```
from .mymagic import MyMagic

def load_ipython_extension(ipython):
    magics = MyMagics(ipython)
    ipython.register_magics(magics)
```

mymagic.py:
```
from IPython.core.magic import Magics, magics_class, line_cell_magic
import argparse
import cx_Oracle
import pandas as pd
from getpass import getpass

@magics_class
class MyMagics(Magics):

    def __init__(self, shell):
        super(MyMagics, self).__init__(shell)
        # [some DB connection settings]


    def _connect(self):
        # Ask for credentials if needed
        if not self.db_user:
            self.db_user = input("Please enter database user name: ")
        if not self.db_pswd:
            self.db_pswd = getpass("Please enter database password: ")

        db_cstr = "{usr}/{pwd}@{host}:{port}/{db}"
        db_cstr = db_cstr.format(...)
        self.db_conn = cx_Oracle.connect(db_cstr, encoding='UTF-8')


    def _query(self, query, index_col, parse_dates):
        return pd.read_sql(query, self.db_conn)


    @line_cell_magic
    def mymagic(self, line = None, cell = None):
        """Run SQL query against backend and get results in a pandas data frame"""

        # [parse line to args]
        
        try: 
            self._connect()
        except DatabaseError as e:
            print(e)
            return None

        try: # Execute query and save results to notebook
            self.shell.user_ns[args.dataframe] = self._query(cell)
        except pd.io.sql.DatabaseError as e:
            print(e)
            return None

        return self.shell.user_ns[args.dataframe].head()
```

**Comment by hellbe** [comment]
Also, fortgot to mention, I'm using JupyterLab

**Comment by takluyver** [comment]
Does it work in `notebook`?

**Comment by hellbe** [comment]
Tried and got the same problem, the password prompt appears in the server terminal window.

**Comment by hellbe** [comment]
I'm really not familiar with the source for ipykernel by started reading a bit, I suspect the [_forward_input()](https://github.com/ipython/ipykernel/blob/master/ipykernel/ipkernel.py#L162-L178) function isn't working as expected due to the order of execution, the last line looks critical re-referencing to the [internal getpass()](https://github.com/ipython/ipykernel/blob/master/ipykernel/kernelbase.py#L669).

Does the instance and getpass import of my magics somehow precede this in execution? 

And as a workaround, could I call the kernel getpass function directly instead maybe?

**Comment by hellbe** [comment]
The workaround mentioned above works for me (including startup load) using the existing parent magic class ipython reference:
```
pwd = self.shell.kernel.getpass()
```

**Comment by takluyver** [comment]
I've figured it out. When you do `from getpass import getpass`, your module stores a reference to the function. We later replace `getpass.getpass` with the function that talks to the frontend, but you've still got a reference to the old function, which we can't easily replace.

So instead of doing this:

```python
from getpass import getpass
...
getpass()
```

You need to do this:

```python
import getpass
...
getpass.getpass()
```

**Comment by hellbe** [comment]
Ah, makes perfect sense. Thanks for sorting it out @takluyver! :1st_place_medal:
