### ISSUE TITLE
Please implement message-based interruption

### ISSUE THREAD

**Issue by martixingwei** [ipython/ipykernel#309]
I tried to launch a remote kernel, which is not interruptible through SIGINT from jupyter, so I put `"interrupt_mode":"message"` in my kernel.json. However, after actually launched the kernel, it cannot be interrupted in this way and output `[IPKernelApp] WARNING | Unknown message type: 'interrupt_request'`.

It seems that message-based interruption is not implemented in ipykernel.

**Comment by takluyver** [comment]
That's not there for users to switch, that's for kernels to declare how they should be interrupted. IPykernel uses signal based interrupting, so it doesn't ask for interrupt messages.

We're working on ways to allow interrupting a remote kernel using a signal, but it's involving quite a bit of design work.
