### ISSUE TITLE
tests/_asyncio.py broken after tornado 5.0.0 update

### ISSUE THREAD

**Issue by semperstew** [ipython/ipykernel#313]
Hi. I'm running JupyterHub on AWS EMR following the directions on [this page](https://aws.amazon.com/blogs/big-data/running-jupyter-notebook-and-jupyterhub-on-amazon-emr/) and using the bootstrap script located at: s3://aws-bigdata-blog/artifacts/aws-blog-emr-jupyter/install-jupyter-emr5.sh

Everything was working great until today when tornado updated to 5.0.0. Now I'm receiving errors during the bootstrap step.

```bash
changing mode of /usr/local/bin/jupyter-kernelspec to 755
  changing mode of /usr/local/bin/jupyter-kernel to 755
  changing mode of /usr/local/bin/jupyter-run to 755
  *** Error compiling '/mnt/tmp/pip-build-sla8heey/ipykernel/ipykernel/tests/_asyncio.py'...
    File "/mnt/tmp/pip-build-sla8heey/ipykernel/ipykernel/tests/_asyncio.py", line 14
      async def task():
              ^
  SyntaxError: invalid syntax
```

Any ideas how to solve this?

**Comment by minrk** [comment]
I'm not familiar with EMR, but if the installation is failing on that step, there is a bug in the installation machinery, as Python does not normally fail installation on bytecompilation failure. This is a file that is only valid in Python 3 and will only be imported on Python 3, so should be safely ignored on Python 2. A workaround is to rebundle an ipykernel tarball without this file.
