### ISSUE TITLE
Incorrect sideplots in inline matplotlib backend

### ISSUE THREAD

**Issue by ksunden** [ipython/ipykernel#351]
Inline backend is producing images which differ from other matplotlib backends when using sideplots with axes made by using `mpl_toolkits.axes_grid1`

```python
%matplotlib inline
from matplotlib import pyplot as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable
import numpy as np
np.random.seed(1)
ax = plt.gca()
x = y = np.linspace(0,10,10)
z = np.random.random((10,10))
plt.pcolor(x,y,z)
sidex = make_axes_locatable(ax).append_axes("top", 1)
sidex.plot(x, np.random.random(10))
```

Expected Output (with qt backend): 
![figure_1](https://user-images.githubusercontent.com/2501846/46042417-ef993980-c0da-11e8-9b0d-a73d19d625e7.png)

Actual Output
![figure_2](https://user-images.githubusercontent.com/2501846/46042453-0c357180-c0db-11e8-864a-4121cebecef5.png)

Examples on [matplotlib docs](https://matplotlib.org/mpl_toolkits/axes_grid/users/overview.html) produce similar results.

ipykernel: 4.9.0
Python 3.6.6, 3.7.0
matplotlib 3.0.0
numpy 1.15.2

**Comment by ianthomas23** [comment]
I am closing this as it now works as expected. Here is the output running in Jupyter when using `qt` and `inline` backends:

<img width="652" alt="Screenshot 2024-05-14 at 10 14 50" src="https://github.com/ipython/ipykernel/assets/580326/93f52a62-5759-404c-8c3f-a754114ae58b">
<img width="594" alt="Screenshot 2024-05-14 at 10 15 11" src="https://github.com/ipython/ipykernel/assets/580326/b46cee63-2e40-4065-8128-ed83e6d65ce4">
