### ISSUE TITLE
Reflect in setup classifiers that support for python <3 was dropped

### ISSUE THREAD

**Issue by maapxa** [ipython/ipykernel#353]
Support for python < 3 was dropped in [this](https://github.com/ipython/ipykernel/commit/91c780f67caa48e94351633ce8d88ee3cb1eb489#diff-2eeaed663bd0d25b7e608891384b7298) commit. Would be nice to have that changed in the [`classifiers`](https://github.com/ipython/ipykernel/blob/master/setup.py#L110) section, and [test requirements](https://github.com/ipython/ipykernel/blob/master/setup.py#L97), in `setup.py`

**Comment by felipeek** [comment]
I'm getting an error trying to install ipykernel from pip and I think this is related to this issue.

```
Collecting ipykernel>=4.5.1 (from ipywidgets==7.1.0->halo==0.0.14->infraboxcli)
  Using cached https://files.pythonhosted.org/packages/e1/cb/0129f461e8a4823fe662df4992d6ce8a0b593a5e86c6de78d4b882a0cf44/ipykernel-5.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    ERROR: ipykernel requires Python version 3.4 or above.
```
This happens because `https://github.com/ipython/ipykernel/blob/master/setup.py` has
`#!/usr/bin/env python`

Python 3 is called using `python3`, not `python`
