### ISSUE TITLE
run all can reorder executions on Windows

### ISSUE THREAD

**Issue by stonebig** [ipython/ipykernel#356]
https://github.com/jupyter/notebook/issues/4052

**Comment by stonebig** [comment]
going back to ipykernel-4.9.0 for now, until further direction

**Comment by minrk** [comment]
This is a bug in 5.0, we will fix it and release 5.0.1. For those affected, pinning `ipykernel<5` will avoid the problem. FWIW, I cannot reproduce it with the given notebooks, so it does seem to be isolated to some environment that I have not yet identified.

**Comment by minrk** [comment]
From reports, this appears to be a bug confined to Windows.

**Comment by minrk** [comment]
ipykernel 5.1 is out with the fix
