### ISSUE TITLE
ERROR: ipykernel requires Python version 3.4 or above

### ISSUE THREAD

**Issue by santanu-tripathy** [ipython/ipykernel#364]
I am using Ubuntu 16.04 lts. I have installed python3.7 lately. Though my default python binary is python2.7. When I am trying to install ipykernel with the following command 
>python -m pip install ipykernel

It is giving the following errors

>ERROR: ipykernel requires Python version 3.4 or above.

Please help me

**Comment by jamesmyatt** [comment]
`python3 -m pip install ipykernel`

**Comment by santanu-tripathy** [comment]
Yeah,
Today I found out that and the problem is solved.
