### ISSUE TITLE
Wait for comm message synchronously

### ISSUE THREAD

**Issue by saulshanabrook** [ipython/ipykernel#369]
I am opening a comm from the kernel and waiting to get one message back from the frontend. I would like to wait on this message synchronously.

With the recent addition of top level async await support, I had hoped I would be able to do something like this:

```python
from ipykernel.comm import Comm

COMM_ID = 'some-unique-iddd'

my_comm = Comm(target_name=COMM_ID, data=SOME_DATA)
future = asyncio.Future()

@my_comm.on_msg
def _recv(msg):
    future.set_result(msg['content']['data'])
await future
```

However, this will not return ever. Once the cell is finished executing (after you cancel it manually), then the future can be awaited and will return.

I have tried a bunch of other things as well, like sleeping or using generators, none of which I can get to work.

Why do I want this? I need to send some data to the frontend, transform it there, then send it back to Python for further transformation, then use Jupyter's default output machinery (`display` or other mimerender things) to show the results to the users.

My assumption here is that the Python kernel is blocking on receiving the incoming com message while it is executing the code.

I have tried to look into the internals here to figure out what is blocking on what. Does anyone have any tips on where I should look in other to patch this in ipykernel or to hack around this?

**Comment by saulshanabrook** [comment]
Thanks to @tonyfast for showing me how to get around this by just updating the display once the message comes in 👍 

```
from ipykernel.comm import Comm
import IPython

COMM_ID = 'some-unique-iddd'
my_comm = Comm(target_name=COMM_ID, data=SPEC)
display_id = IPython.display.display("dfd", display_id=True)
@my_comm.on_msg
def _recv(msg):
    display_id.update(msg['content']['data'])
```

**Comment by pkerpedjiev** [comment]
Is there a way to do what @saulshanabrook originally asked?

I would like to pull some data from a front-end widget by sending a message and then retrieve it in Python. I trigger the JS function call by sending a message but I can't receive the returned message because the (Python) calling function is sitting on the thread preventing message receive callback from being called.
