### ISSUE TITLE
IPykernel triggers repeated DeprecationWarnings due to input_splitter

### ISSUE THREAD

**Issue by CAM-Gerlach** [ipython/ipykernel#375]
@minrk When certain commands are run (e.g. ``print(<object>)``) in Spyder's Console, ``ipykernel`` (including the latest version, 5.1.0) raises one or something many ``DeprecationWarning``s like the following every time enter is pressed, and often doesn't run the command until forced with ``Shift-Enter``:

```python-traceback
C:\Anaconda3\envs\pyart\lib\site-packages\ipykernel\ipkernel.py:448: DeprecationWarning: `input_splitter` is deprecated since IPython 7.0, prefer `input_transformer_manager`.
  status, indent_spaces = self.shell.input_splitter.check_complete(code)
```

This is not only annoying, but actually seriously affects the functionality by not allowing the user to run the command normally. It was first reported in spyder-ide/spyder#8103 and "fixed" in spyder-ude/spyder-kernels#59 , but it doesn't seem like it was actually reported here where it belongs for some reason, and instead that "solution" was just to suppress ``DeprecationWarnings`` from ``ipykernel`` entirely.

Therefore, I wanted to give you a heads up before it breaks! [Here](https://github.com/ipython/ipykernel/blob/35b1d1a823dd22a0fe4eb99e89463c2527a11271/ipykernel/ipkernel.py#L448) 's the relevant line that's triggering it, for your convenience; presumably fixing it would involve updating it to use ``input_transformer_manager`` instead but I'm no expert. Thanks!

**Comment by ccordoba12** [comment]
@CAM-Gerlach, this is an easy fix. I think you should go for it.

**Comment by CAM-Gerlach** [comment]
Okay, sure—I'll add it to the list. So it really is as easy as just replacing the above with ``self.shell.input_transformer_manager.check_complete(code)``? It indeed looks like a drop-in according to [the docs](https://ipython.readthedocs.io/en/stable/api/generated/IPython.core.inputtransformer2.html#module-IPython.core.inputtransformer2)...

**Comment by ccordoba12** [comment]
Yes, it is.

**Comment by dcedgren** [comment]
This issue is still occurring with Spyder 4.0.1 and IPython 7.12.0. It seems like this issue must be affecting many users and it was first noticed in Oct. 2018. Perhaps someone can prioritize merging the pull request to finally get this resolved?

**Comment by CAM-Gerlach** [comment]
@blink1073 @minrk ^

**Comment by dcedgren** [comment]
Thanks blink!
