### ISSUE TITLE
Objects not created when "%%time" is used

### ISSUE THREAD

**Issue by indrajitsg** [ipython/ipykernel#401]
**Describe the bug**

When I use "%%time" in a cell which has an assignment, the assigned object does not get created.

**Screenshots**
![jupyter1](https://user-images.githubusercontent.com/10430320/56582969-20503b80-65f6-11e9-8a7d-0441cc595990.JPG)

It does not work in both JupyterLab and Jupyter Notebook.

Regards,
Indrajit

**Comment by jasongrout** [comment]
I'll note that I also reproduced this (ipykernel 5.1.0 from conda-forge). When I tried using just the ipython command line console, it worked, so it makes me think that it is an ipykernel issue rather than an ipython issue.

**Comment by vladserkoff** [comment]
Looks like it will be fixed in the next release https://github.com/ipython/ipython/issues/11659

**Comment by cdeil** [comment]
I think this issue was fixed in the IPython 7.5 release:
https://ipython.readthedocs.io/en/stable/whatsnew/version7.html#ipython-7-5-0

Close this issue?

**Comment by arogozhnikov** [comment]
updating to 7.5.0 solved the problem for me

**Comment by indrajitsg** [comment]
@arogozhnikov How did you update the IPython kernel?

**Comment by arogozhnikov** [comment]
@indrajitsg I've updayed IPython, not ipykernel alone

**Comment by AwasthiMaddy** [comment]
@indrajitsg `pip install --upgrade ipython` would update ipython kernel to newer version 7.5 and you can get rid of this error.

**Comment by indrajitsg** [comment]
Sure thanks. Will close this.
