### ISSUE TITLE
Printed output not displayed when using joblib in jupyter notebook

### ISSUE THREAD

**Issue by zaccharieramzi** [ipython/ipykernel#402]
So I am using [joblib](https://github.com/joblib/joblib) to parallelize some code and I noticed that I couldn't print things when using it inside a jupyter notebook.

I tried using doing the same example in ipython and it worked perfectly.

Here is a minimal (not) working example to write in a jupyter notebook cell

```python
from joblib import Parallel, delayed
Parallel(n_jobs=8)(delayed(print)(i) for i in range(10))
```
So I am getting the output as `[None, None, None, None, None, None, None, None, None, None]` but nothing is printed.

Actually, checking the logs of the notebook process, I noticed that the prints happen there. I would like the prints to happen in the notebook, not the logs of the notebook process.

I have written an [SO issue](https://stackoverflow.com/questions/55955330/printed-output-not-displayed-when-using-joblib-in-jupyter-notebook) as well.

From what I understood discussing with [@tomMoral](https://github.com/tomMoral), it may be related to the way the IO handler is passed to the child processes.

**Comment by leliel12** [comment]
+1

**Comment by ZGainsforth** [comment]
+1

**Comment by spizwhiz** [comment]
+1

**Comment by hollywen7** [comment]
+1

**Comment by cossio** [comment]
Bump.

**Comment by GF-Huang** [comment]
2 years nobody care?

**Comment by GF-Huang** [comment]
2 years nobody care?

**Comment by ccordoba12** [comment]
This should have been fixed in ipykernel 6. Please try again.

**Comment by CamHolman** [comment]
+1

**Comment by zaccharieramzi** [comment]
@ccordoba12 it indeed works now with `ipykernel==6.16.0`.
Closing this.

**Comment by jmigual** [comment]
ipykernel 6.20.1 still failing

**Comment by cfd0** [comment]
ipykernel 6.28.0 still failing

**Comment by davidbrochart** [comment]
ipykernel v6.29.0 improved the situation for threads, but I think joblib uses processes?
Maybe @krassowski has ideas, since he did all the work in #1186.

**Comment by nshaff3r** [comment]
ipykernel 6.29.4 working on vs code jupyter extension but not a jupyter notebook

**Comment by juhaszp95** [comment]
Still failing on ipykernel 6.29.5.
