### ISSUE TITLE
5.1.2 Release

### ISSUE THREAD

**Issue by MSeal** [ipython/ipykernel#420]
The changes list: https://github.com/ipython/ipykernel/compare/v5.1.1...master is quite small. 
#396 
#408
#405
#394
and #412 (with #419 fixing an issue with that PR)
There's no interface changes, just internal improvements which should justify a patch release imo.

@minrk or @Carreau perhaps one of you could ferry this to a release? We're wrapping up the 5.6 release process for nbconvert this week and it'd be great if this was out first.

**Comment by willingc** [comment]
I'll draft a quick PR to update the Changelog for 5.1.2.

**Comment by blink1073** [comment]
Thanks @willingc!  I'll cut a release once that one finishes CI.

**Comment by blink1073** [comment]
https://github.com/ipython/ipykernel/releases/tag/v5.1.2

**Comment by blink1073** [comment]
Shucks, my release script didn't take into account the wheel configuration, I need to cut a new release.

**Comment by blink1073** [comment]
Ah, nevermind, there is only one wheel now, we dropped py27 compat.  All good!

**Comment by MSeal** [comment]
Awesome thanks everyone for helping get that released!
