### ISSUE TITLE
Release 4.10.1

### ISSUE THREAD

**Issue by ccordoba12** [ipython/ipykernel#423]
This could be perhaps the last Python 2 release of ipykernel. We need it to solve a bug when passing non-ascii characters to `input` calls, that only occurs in Python 2.

This was reported by one of the Spyder users and fixed by @steff456, who is part of the Spyder team, in PR #414.

Thanks for your help!

**Comment by blink1073** [comment]
I'll get this out today.  Hi @ccordoba12!

**Comment by ccordoba12** [comment]
Hey @blink1073!! Long time no see!

Thanks a lot for your help!

**Comment by blink1073** [comment]
All set!  https://github.com/ipython/ipykernel/releases/tag/v4.10.1

**Comment by ccordoba12** [comment]
Thanks Steve!!
