### ISSUE TITLE
Debugging Protocol and xeus-python

### ISSUE THREAD

**Issue by saulshanabrook** [ipython/ipykernel#466]
I left a comment on the xeus incorporation JEP asking whether we should put resources into getting ipykernel compatible with the new debugger protocol or into making the xeus-kernel feature complete: https://github.com/jupyter/enhancement-proposals/pull/44#issuecomment-564698400

I wanted to open an issue here to raise visibility for that conversation and see if anyone who is working on ipykernel has opinions either way.

**Comment by SylvainCorlay** [comment]
We decided to have the conversation in https://github.com/jupyterlab/debugger/issues/274 and not over several scattered issues. Closing this here.
