### ISSUE TITLE
do_inspect lets ipython compute the info twice

### ISSUE THREAD

**Issue by jankatins** [ipython/ipykernel#51]
Found this while trying to understand what is needed to make a decorated method get the same signature/completions as the original one, even on py2.7.

From https://github.com/ipython/ipykernel/blob/master/ipykernel/ipkernel.py#L247:

```
    def do_inspect(self, code, cursor_pos, detail_level=0):
        name = token_at_cursor(code, cursor_pos)
        info = self.shell.object_inspect(name) # computes the complete info
[...]
        if info['found']:
            info_text = self.shell.object_inspect_text(
                name,
                detail_level=detail_level,
            ) # computes it again as a first step
            data['text/plain'] = info_text
[...]
```

IMO it would be ok to replace the first `self.shell.object_inspect(...)` with a `info = self.shell._object_find(name)` and then use `if info.found:`. The problem is I don't understand what the `with self.builtin_trap:` in the `object_inspect` method does ([source](https://github.com/ipython/ipython/blob/master/IPython/core/interactiveshell.py#L1608)) and if that's already needed for `self.shell._object_find`.

**Comment by minrk** [comment]
That makes good sense to me. I just want to avoid calling private APIs in IPython from ipykernel. I think we need to take a pass on oinspect in IPython to make a few more ways to call its pieces.

**Comment by JanSchulz** [comment]
oinspect probably also needs a pass as `inspect.getfullargspec` is deprecated ( https://docs.python.org/3/library/inspect.html#inspect.getfullargspec and https://github.com/matplotlib/matplotlib/pull/5014#issuecomment-137253854) and using the new `Signature` interface will help with things like getting the proper signature from decorated functions (see https://github.com/matplotlib/matplotlib/pull/4829#issuecomment-137912544 and following comments)
