### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by itamarst** [ipython/ipykernel#515]
Once this is released, https://github.com/ipython/ipython/issues/10516 will finally be fixed. So if you have the time, a release would be welcome to all those Windows users.

**Comment by blink1073** [comment]
Hi @itamarst, which features are missing?  As far as I can tell all merged PRs were released in 5.3.

**Comment by itamarst** [comment]
Oh, sorry, guess it is, yeah.

**Comment by blink1073** [comment]
No worries!
