### ISSUE TITLE
PPID is not necessarily 1 when parent frontend is killed

### ISSUE THREAD

**Issue by xuesoso** [ipython/ipykernel#517]
Hi, I have raised this issue separately on [jupyter-console](https://github.com/jupyter/jupyter_console/issues/221)

The problem I noticed is that when I directly close the frontend program that called "jupyter-console" (e.g. my terminal), it leaves the "ipykernel_launcher" running in the background. What I expected to happen is that the kernel session created by "jupyter-console" will be killed whenever its host frontend program is killed. I think I have some clues as to the reason why.

First to provide some of the relevant observations:
1. On a remote machine without interactive login session, killing the parent frontend (e.g. a Tmux session or terminal) hosting the Jupyter console will lead to the expected killing of ipykernel on the background. 
2. On another machine running Manjaro Gnome, killing the parent frontend (e.g. a Tmux session or terminal) will not kill the ipykernel subprocess. I can see that it's still dangling in the background.

Chasing down the rabbit hole, I found additional observations:
1. "ipykernel/parentpoller.py" : is responsible for continuous monitoring of parent process that spawned ipykernel. "Line 36" makes the assumption that if the parent of orphaned process is killed, its ID gets set to "1", in which case the kernel will exit itself.
![parentpoller_relevant_code](https://user-images.githubusercontent.com/15006047/85074085-d66ad300-b170-11ea-90c2-772bb28c553e.png)
2. After adding in a line to log the parent process ID, I found that on the Manjaro Gnome machine, the initial parent process ID transfers from the "jupyer-console":
![initial_ppid](https://user-images.githubusercontent.com/15006047/85072650-488de880-b16e-11ea-904e-2715f0b94b0b.png)
after killing the initial parent process to:
![post_parent_killed_ppid](https://user-images.githubusercontent.com/15006047/85072702-622f3000-b16e-11ea-823e-52fee09b6e62.png)

![ppid](https://user-images.githubusercontent.com/15006047/85072943-c05c1300-b16e-11ea-87c4-638dc3ff0f75.png)

A few additional [posts](https://unix.stackexchange.com/questions/149319/new-parent-process-when-the-parent-process-dies/177361#177361) suggest that the parent ID of orphaned processes may not be necessarily set to 1 if there are ancestor processes. Since [Gnome 3.34](https://blogs.gnome.org/benzea/2019/10/01/gnome-3-34-is-now-managed-using-systemd/) (and maybe a few more other distributions), there is a shift towards handing off more processes to systemd. Thus when orphaned child arises, it does not get handed off to "init" with a PID of 1. It seems ipykernel may require a special handling to prevent undead backends that consume system resources. A suggestion would be to kill the ipykernel whenever PPID == 1 or PPID == "that of systemd".

**Comment by bluss** [comment]
I noticed this after having used/adapted the same code into my project (by necessity, I discovered).

jupyter-client already sets JPY_PARENT_PID, I'm wondering why it's not using that. The parent pid is known, and could be used for comparison. There can of course always be some obscure reason, that it doesn't work on some platform.

(Alternatively, is it viable to monitor the parent pid and take action if it changes, i.e current process was reparented?)
