### ISSUE TITLE
Correct installation of ipykernel in virtual environment

### ISSUE THREAD

**Issue by rsmith31415** [ipython/ipykernel#52]
I was trying to install the IPython kernel (using python 2.x) in a new virtual environment but I didn't find very clear instructions. 

I installed ipykernel and then used `jupyter kernelspec install-self --user`. Is this the correct approach? Is this the equivalent of `IRkernel::installspec()` in the IR kernel? Maybe I should use `ipython kernelspec install-self` (related to this [issue](https://github.com/jupyter/jupyter/issues/23))

**Comment by JanSchulz** [comment]
The above worked in my case:

```
activate <env>
conda install jupyter
jupyter kernelspec install-self --user
```

I had to edit the kernel spec to get a proper name, which identified the env.

**Comment by rsmith31415** [comment]
Yes, that works but in my case, I only want to install `jupyter_client`.  I think `conda install jupyter`  installs everything (qtconsole, notebook). What did you have to change in your kernels.json? Because that sounds similar to another [issue](https://github.com/jupyter/notebook/issues/397#issuecomment-137993057) that I encountered today.

**Comment by JanSchulz** [comment]
ok, not sure in which conda package `jupyter kernelspec` is in.

In my case, I only changed the display name so that I could identify my env in the notebook.

**Comment by minrk** [comment]
In master, the entrypoint is `ipython kernel install`, but for 4.0 this is only available as `python -m ipykernel.kernelspec`.

**Comment by rsmith31415** [comment]
Thanks. I will remember this the next time. What will happen to `jupyter kernelspec install-self --user`?

**Comment by Carreau** [comment]
`jupyter kernelspec install-self` does not make sens as jupyter have no default language. `ipython kernelspec install-self` should still work (if ipykernel is installed), but ipython itself now ship without the "kernel" part. So it is in `ipykernel` now.

**Comment by rsmith31415** [comment]
If I remember correctly, it is possible to install ipykernel without ipython. So in that case, `ipython kernel install` won't work, but `python -m ipykernel.kernelspec` will work. Furthermore, we shouldn't use `jupyter kernelspec install-self` anymore. Is that correct?

**Comment by Carreau** [comment]
I doubt ipykernel comes without IPython, but regadless, non you shoudln't use `jupyter kernelspec install-self`.

**Comment by rsmith31415** [comment]
You're absolutely right. I just checked and ipykernel installs ipython. Then both options will work. 

Thanks

**Comment by takluyver** [comment]
Kernel installation is now documented here: http://ipython.readthedocs.org/en/latest/install/kernel_install.html

**Comment by poojanarayanc** [comment]
I installed Anaconda. Understood the evironments and created a new environment with anaconda in it.
[myenv] shows at the prompt. I know there are loads of packages installed in that env. 
But both Spyder and Jupyter don't import them.
I get an error such as No module named 'beautifulsoup4'.

What am I missing?

**Comment by takluyver** [comment]
The IPython kernels that both Jupyter and Spyder talk to are probably not running in your virtualenv. You need to either:

Install `ipykernel` inside the env, and install the kernel spec as described [here](http://ipython.readthedocs.org/en/latest/install/kernel_install.html).

*OR*

Install and run all of Jupyter inside the env (`conda install jupyter`)

**Comment by poojanarayanc** [comment]
Thanks takluyver. 

I did this 

conda create -n myenv python=3 ipykernel
activate myenv
python -m ipykernel install --user

A load of new packages were downloaded and installed. I can now fire up jupyter from myenv and work fine. 

But I want all those packaged that Anaconda came with to be in this package. If I do the same thing that I did above in my root, I still am having problems importing my other packages into jupyter.

What do you suggest? Thanks a lot.

**Comment by takluyver** [comment]
Conda envs are independent, so when you create a new one, it doesn't inherit the packages in the 'root environment' of Anaconda. You can reinstall all those packages in the environment by running `conda install anaconda` with the environment active.

**Comment by takluyver** [comment]
Oh, just saw that you'd worked that out. Install other packages as needed, e.g. `conda install beautifulsoup4`.

**Comment by poojanarayanc** [comment]
Yes :) Thank you. 

Can I do anything I do in Spyder for example on Jupyter? I'm starting out with Jupyter now. It seems much nicer than Spyder. Although that there won't be a variable explorer like how there is on Spyder. Or is there a way? 

Thank you.

**Comment by takluyver** [comment]
You should be able to run any of the same code; some people prefer each interface. It's a bit awkward to do a variable explorer in the Jupyter notebook, but I think someone did an extension for it. I can't find it now, though - someone else may be able to point you to it.

**Comment by vsafinia** [comment]
`conda create -n py27 python=2.7
source activate py27
conda install notebook ipykernel
ipython kernelspec install-self`
