### ISSUE TITLE
please i need help with these error am encountering. 

### ISSUE THREAD

**Issue by tony-12** [ipython/ipykernel#544]
standard_codes = "/root/malware/ops.txt"
app_dir = "/root/malware/decompiled/"

ef std_codes_list(standard_codes):

    std_codes = []

    with open(standard_codes,'r') as fp:
        for cnt, line in enumerate(fp): 
            read_lines = fp.read();
            read_lines = read_lines.split("\n")
            std_codes = read_lines
            std_codes.pop() 

    return std_codes

and after running the whole program i am getting this error
IsADirectoryError                         Traceback (most recent call last)
<ipython-input-108-d09f88270c89> in <module>
----> 1 std_codes = std_codes_list(standard_codes)
      2 
      3 apk_list = pickle.load(open('apk_pickle_list.pkl', 'rb'))
      4 
      5 for each_apk in apk_list:

<ipython-input-104-65deaac4f375> in std_codes_list(standard_codes)
      3     std_codes = [] #empty list which will later contain all the standard op-codes read from the ops.txt file
      4 
----> 5     with open(standard_codes,'r') as fp:
      6         for cnt, line in enumerate(fp): # reading each op-code in the txt file
      7             read_lines = fp.read();

IsADirectoryError: [Errno 21] Is a directory: '/root/malware/ops.txt'

**Comment by blink1073** [comment]
Hi @tony-12, this looks like a more general Python code question, please use another forum such as StackOverflow.
