### ISSUE TITLE
Extract inline backend from ipykernel and matplotlib magics from IPython

### ISSUE THREAD

**Issue by martinRenou** [ipython/ipykernel#588]
There is currently a big special case for the Matplotlib library in ipykernel and IPython.

IPython provides a `%matplotlib`magic that allows choosing the current Matplotlib backend that is being used. For the sake of modularity, and in order to get rid of the special case, we should maybe extract this magic out of IPython and put it in Matplotlib (when Matplotlib is installed, it installs this magic).

ipykernel provides the Matplotlib inline backend, this should maybe be extracted from ipykernel and put in a separate package (Matplotlib?). This new module should maybe contain the [configure_inline_support](https://github.com/ipython/ipython/blob/master/IPython/core/pylabtools.py#L363) method that currently lives in IPython, and should be called when `%matplotlib inline` is invoked.

Those two improvements would help clean up the current ipykernel-IPython-Matplotlib relationship.

@SylvainCorlay @Carreau @tacaswell

**Comment by Carreau** [comment]
@martinrenou do you consider this finished now that IPython rely on `matplotlib-inline` ?

**Comment by martinRenou** [comment]
Yes! Let's close it

**Comment by SylvainCorlay** [comment]
However, we should eventually get back to core IPython and remove the hardcoded dict "backend name" -> "module".
