### ISSUE TITLE
Cannot python3 -m ipykernel install when ipykernel is installed in read-only directory

### ISSUE THREAD

**Issue by jellelicht** [ipython/ipykernel#592]
When running
`python3 -m ipykernel install --user --name=<my-venv>`, I see:

> [Errno 13] Permission denied: '/tmp/tmpok8jp1dc_kernels/python3/kernel.json'

I pinpointed the problem to the following line:

https://github.com/ipython/ipykernel/blob/da44c7c7b8d60016e68408fefb438b511d2aa283/ipykernel/kernelspec.py#L78

I have the issue that the directory pointed to by `RESOURCES` is read-only (by design), which leads to `path` being read-only as well, after being populated by `shutil.copytree`. This subsequently leads to some permission denied errors when trying to write kernel.json. 

This is easily remedied by something like the following:
```python
import stat
mode_flags = stat.S_IWUSR
    m = os.stat(path).st_mode
    if not m & mode_flags:
        os.chmod(path, m | mode_flags)
```

If this is an acceptable (upstream-able) fix for my admittedly weird situation, I can work on a proper PR. 
Thanks!

**Comment by blink1073** [comment]
> I can work on a proper PR

Yes, please!

**Comment by jellelicht** [comment]
@blink1073 after an embarrassing mistake, everything seems to be in order.
