### ISSUE TITLE
comm changes break jupyter_client CI

### ISSUE THREAD

**Issue by Carreau** [ipython/ipykernel#602]
See https://github.com/jupyter/jupyter_client/pull/625

cc @SylvainCorlay might have insights as to why and how to fix it ?

**Comment by jtpio** [comment]
It might be similar to the one spotted in the `ipywidgets` documentation: https://github.com/jupyter-widgets/ipywidgets/issues/3154

**Comment by SylvainCorlay** [comment]
I have not looked into it, but I plan on making a pass on ipykernel to

- move some of the debugger logic from the base class kernelbase to ipkernel,
- look into that CI issue,

by the end of the week.

**Comment by Carreau** [comment]
No worries, just to let you know, for now we might revert CI in jupyter-client to not install from pre – I want to make a release if possible. As long as it's tracked that's fine.

**Comment by SylvainCorlay** [comment]
I think this should be fixed. To be confirmed when we make another pre-release with the current state of the master branch.

**Comment by Carreau** [comment]
As far as I can tell with ipykernel 6.0.0b0 and ipywidgets 8.0.0a4 this seem to work.
Should we close ?

**Comment by SylvainCorlay** [comment]
I think so.

**Comment by jtpio** [comment]
> It might be similar to the one spotted in the `ipywidgets` documentation: [jupyter-widgets/ipywidgets#3154](https://github.com/jupyter-widgets/ipywidgets/issues/3154)

Tests and the docs build seem to be passing now yes: https://github.com/jupyter-widgets/ipywidgets/pull/3168

**Comment by vidartf** [comment]
Thanks for fixing. If someone has rights to close issue, it can be cleaned up!

**Comment by jasongrout** [comment]
> I think so.

It would be nice if we had a link to the pr that fixed this, but not urgent or crucial...
