### ISSUE TITLE
jupyter_client-6.2 support

### ISSUE THREAD

**Issue by blshkv** [ipython/ipykernel#664]
it was highlighted that the current version does not support jupyter_client-6.2, see https://bugs.gentoo.org/789000

Please fix and test it, also adjust the requirements accordingly:
https://github.com/ipython/ipykernel/blob/master/setup.py#L81

**Comment by ccordoba12** [comment]
That version was yanked in PyPI, so you shouldn't use it. The team is preparing version 7.0, and support for it is already in the master branch here.

**Comment by SylvainCorlay** [comment]
Should we close this issue?

**Comment by ccordoba12** [comment]
I think so because it shouldn't be packaged downstream.

**Comment by blshkv** [comment]
thanks guys!
