### ISSUE TITLE
ipykernel 6.0 release planning

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipykernel#677]
IPykernel 6.0 will be a major release (debugger support, tornado coroutines removed, and more).
We have tagged a few pre-releases, but I think we should try to identify things that we want to resolve for 6.0:

 - issues introduced by the latest changes,
 - outstanding bugs that should be fixed in this milestone,
 - deprecated APIs and major changes we want to remove completely in this occasion.

cc @ccordoba12 @minrk @Carreau @martinRenou @afshin

**Comment by Carreau** [comment]
As far as I can tell the few left issues are fixed, or can be postpone, and we had no issues reported in the last two weeks, do you believe it is time for a release ?

**Comment by Carreau** [comment]
There was only one PR in the last 2 weeks, any thoughts on making a RC ? @blink1073 I think you are the one who usually releases?

**Comment by blink1073** [comment]
RC sounds good, will cut one today

**Comment by Carreau** [comment]
> RC sounds good, will cut one today

Thanks ! <3

**Comment by blink1073** [comment]
https://github.com/ipython/ipykernel/releases/tag/6.0.0rc0

**Comment by Carreau** [comment]
I've tagged all merged PRs and closed issue of the past ~1 year with the correct milestone and sent a PR to upddate the changelog.

**Comment by ccordoba12** [comment]
Sorry for showing up late here. I ran some our kernel test suite with ipykernel 6 and everything seems to be working fine:

https://github.com/spyder-ide/spyder-kernels/pull/292

What's the plan for the final release? I'm asking because we have a bunch of other tests in Spyder itself and I'd like to run them too. So if you could give me until this weekend, it'd be great.

**Comment by blink1073** [comment]
> So if you could give me until this weekend, it'd be great.

No problem!  I'll be OOO Friday-Monday, so Tuesday is the earliest I would release anyway.

**Comment by ccordoba12** [comment]
Great! I'll report back with new results then during the weekend.

**Comment by Carreau** [comment]
I've cleaned up a bunch of deprecation in the last week, so we can also do a last RC just in case if there are any concerns.

**Comment by blink1073** [comment]
Yeah, that makes sense to me, I'll cut another RC today.

**Comment by blink1073** [comment]
https://github.com/ipython/ipykernel/releases/tag/6.0.0rc1

**Comment by Carreau** [comment]
🎉

**Comment by blink1073** [comment]
I cut https://github.com/ipython/ipykernel/releases/tag/6.0.0rc2 to pick up https://github.com/ipython/ipykernel/pull/695

**Comment by Carreau** [comment]
I haven't seen any issue beyond #697 I'm not too sure whether this should block a release. 

I think if it's mostly working we should publish 6.0 which will anyway break stuff and make a 6.1 (or 6.0.1) in a week or so. 

@blink1073 let me know if you want me to try to cut the releases.

**Comment by blink1073** [comment]
> let me know if you want me to try to cut the releases.

If you review #698 I can take it from there :smile:

**Comment by Carreau** [comment]
> If you review #698 I can take it from there 😄

Done, thanks, and big hugs !

**Comment by blink1073** [comment]
> Done, thanks, and big hugs !

Thanks!  I'll cut the release tomorrow morning, in case of fall out.  😆

**Comment by Carreau** [comment]
> Thanks! I'll cut the release tomorrow morning, in case of fall out. 😆

No worries, I'm on european timezone so can watch while you are not working.

**Comment by blink1073** [comment]
https://discourse.jupyter.org/t/ann-ipykernel-6-0-release/9804

:rocket:

**Comment by SylvainCorlay** [comment]
Many many thanks for tagging the release @blink1073!

**Comment by SylvainCorlay** [comment]
Now closing the issue.
