### ISSUE TITLE
Python 2.x not working in virtual environment with Python 3.5

### ISSUE THREAD

**Issue by rsmith31415** [ipython/ipykernel#68]
When I create a conda environment with Python 3.5 and then install the notebook, several kernels are correctly detected by the KernelSpecManager (python2 and python3, among others.) However, selecting python2 in the list of kernels actually launches python3:

![screenshot from 2015-10-19 22 15 41](https://cloud.githubusercontent.com/assets/599274/10596908/fc5bac9e-76ae-11e5-96a3-004507fbd751.png)

This is the list of kernels:

```
In [1]: from jupyter_client.kernelspec import KernelSpecManager

In [2]: KernelSpecManager().find_kernel_specs()
Out[2]:
{'bash': '/home/user/.local/share/jupyter/kernels/bash',
 'ir': '/home/user/.local/share/jupyter/kernels/ir',
 'julia-0.4': '/home/user/.local/share/jupyter/kernels/julia-0.4',
 'python2': '/home/user/.local/share/jupyter/kernels/python2',
 'python3': '/home/user/anaconda/envs/py3_jupyter/lib/python3.5/site-packages/ipykernel/resources'}
```

Why did this happen in the first place? Is this a bug?

**Comment by minrk** [comment]
Can you show the contents of `/home/user/.local/share/jupyter/kernels/python2/kernel.json`?

**Comment by rsmith31415** [comment]
Sure.



```
{
 "display_name": "Python 2", 
 "language": "python", 
 "argv": [
  "python", 
  "-m", 
  "ipykernel", 
  "-f", 
  "{connection_file}"
 ]
}
```

**Comment by rsmith31415** [comment]
Looks like [this](https://github.com/jupyter/notebook/issues/397) is causing issues here. What would be a solution in this case? I want to use libraries installed in the active conda environment but also keep both Python 2 and 3 available.

Thanks

**Comment by minrk** [comment]
Yes, so `python` in kernelspec will always refer to the Python of the notebook server's environment. This is why IPython (following Python's own rewrite of the `#!` line of scripts) hardcodes the full path to sys.executable at install time. By manually changing this, as was recommended in jupyter/notebook#397 is explicitly requesting the behavior you are seeing. If you want it to launch with a specific Python, you must specify the absolute path. If you want it to launch with Python 3 or legacy Python, but be sensitive to the env, then you can use `python2` or `python3`.

**Comment by rsmith31415** [comment]
Thanks. Then what do you recommend for new users? Create an environment for Python 2 and another for Python 3, install ipykernel in both, and point the path in kernel.json to the appropriate location inside the environment?

By the way, using `python2` might not work because it uses `/usr/bin/python` and can't find `ipykernel`.

**Comment by minrk** [comment]
I wouldn't suggest that new users modify any kernel.json. I would recommend that they run `python2 -m ipykernel install` and `python3 -m ipykernel install` one time, and be done. They can do this in envs if they wish, or not. If they choose to create new envs and want to install kernels for those envs, run `python -m ipykernel --display-name 'Python <env>'` in the env. This can be done on env creating with virtualenvwrapper, if it's a common enough action.

**Comment by rsmith31415** [comment]
Got it. `python -m ipykernel --display-name 'Python <env>'` looks really useful. Thanks.
