### ISSUE TITLE
`ipykernel.iostream.OutStream.isatty()` should be `True`. 

### ISSUE THREAD

**Issue by real-yfprojects** [ipython/ipykernel#680]
I was redirected from [qtconsole](https://github.com/jupyter/qtconsole). I posted [this Issue](https://github.com/jupyter/qtconsole/issues/486) over there. 

A stream's method isatty should return whether it is an 'interactive' stream. I think that means whether it is an interactive console. 

Although *qtconsole* is an interactive stream their `sys.stdout.isatty()` returns `False`. This is because *qtconsole* uses `ipykernel.iostream.OutStream` as standard streams for `sys.stdout` and `sys.stderr`. This class inherits the method `isatty()` from `io.TextIoBase` which isn't supposed to be an interactive stream by default.

https://github.com/ipython/ipykernel/blob/fda115626dd434f49a4d8f8e55080d5fd2c2e2b9/ipykernel/iostream.py#L276

One of the current main developers of `qtconsole` told me:

> Please open this issue in the ipykernel repo because we can't solve it here and a change as the one you're suggesting will also affect the Jupyter notebook and JupyterLab.

***
This Issue relates to #268 .

**Comment by peendebak** [comment]
@real-yfprojects I don't have a strong opinion on whether the `isatty()` should be patched here, or in qtconsole, but I would like to see this addressed as well. It would solve problems with colored output in spyder (see https://github.com/willmcgugan/rich/pull/1221 and the references there)
