### ISSUE TITLE
v6 String not displayed in tree view

### ISSUE THREAD

**Issue by fcollonval** [ipython/ipykernel#699]
when turning on the debugger, strings are not displayed in the variables panel.

![string_in_tree_view](https://user-images.githubusercontent.com/8435071/123937573-969b1600-d996-11eb-904e-5c03e81369dc.gif)

> This does not happen during a debug session; only in kernel state introspection.

**Comment by JohanMabille** [comment]
This looks like a Jupyter Lab issue since the value is available in the table view. I can see the same issue when using `xeus-python` while the value of the string is available in the `inspectVariable` response.

**Comment by fcollonval** [comment]
Thanks @JohanMabille i'll open the issue there.
