### ISSUE TITLE
6.0.0: `python -m ipykernel install` fails on missing `debugpy`

### ISSUE THREAD

**Issue by kloczek** [ipython/ipykernel#701]
Issue is that there are some issues with `debugpy` like
https://github.com/microsoft/debugpy/issues/652
https://github.com/microsoft/debugpy/issues/595
```console
+ /usr/bin/install build/sphinx/man/python-ipykernel.3 -Dt /home/tkloczko/rpmbuild/BUILDROOT/python-ipykernel-6.0.0-2.fc35.x86_64/usr/share/man/man3
+ /usr/bin/python3 -m ipykernel install --prefix /home/tkloczko/rpmbuild/BUILDROOT/python-ipykernel-6.0.0-2.fc35.x86_64/usr
Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tkloczko/rpmbuild/BUILD/ipykernel-6.0.0/ipykernel/__main__.py", line 2, in <module>
    from ipykernel import kernelapp as app
  File "/home/tkloczko/rpmbuild/BUILD/ipykernel-6.0.0/ipykernel/kernelapp.py", line 42, in <module>
    from .ipkernel import IPythonKernel
  File "/home/tkloczko/rpmbuild/BUILD/ipykernel-6.0.0/ipykernel/ipkernel.py", line 20, in <module>
    from .debugger import Debugger
  File "/home/tkloczko/rpmbuild/BUILD/ipykernel-6.0.0/ipykernel/debugger.py", line 14, in <module>
    import debugpy
ModuleNotFoundError: No module named 'debugpy'
```

**Comment by Carreau** [comment]
https://github.com/ipython/ipykernel/blob/0ffbf254da9b7b9c57f58b68eb454504d1bc00a9/setup.py contain debugpy as a deppendency,  so it's expected it should be installed.... maybe we should update the  what's new.

**Comment by kloczek** [comment]
> https://github.com/ipython/ipykernel/blob/0ffbf254da9b7b9c57f58b68eb454504d1bc00a9/setup.py contain debugpy as a deppendency, so it's expected it should be installed.... maybe we should update the what's new.

No .. this ticket is not about missing modulke in my build env :)
It is about problems with packaging and using module which is not ready for even python 3.8 :(

**Comment by kloczek** [comment]
FYI temporary I've added in rpm spec file deselecting those units which are using `debugpy` so no rush :)

**Comment by bnavigator** [comment]
@klcozek: debugpy is available in PyPI and conda. RPMs can be built from it, I just [submitted one to openSUSE](https://build.opensuse.org/package/show/devel:languages:python/python-debugpy) (because of ipykernel 6). Your problems are with your build environment, not with ipykernel.

**Comment by kloczek** [comment]
Please check tumbleweed reposytory. In that repository there is no `debugpy` for python +3.8.

**Comment by bnavigator** [comment]
Because it is not submitted to Factory yet. Check the link. The devel project successfully builds python38-debugpy and python39-debugpy. And I can also [sucessfully build ipykernel 6.0.0](https://build.opensuse.org/package/show/home:bnavigator:branches:devel:languages:python:jupyter/python-ipykernel) with a passing test suite.

**Comment by kloczek** [comment]
Just checked and looks like in tumbleweed reposytory is python-ipykernel-5.4.3-1.3 which does not requires on build stage `debugpy`.
`debugpy`  1.3.0 (as it is in https://github.com/microsoft/debugpy/issues/652) fails for me on compile pyc files on python 3.8.11 because it uses python 2.x syntax). So SuSE can build that package only if they are not generating during build those files.

**Comment by bnavigator** [comment]
You can just follow my links, check the build logs there and realize that your statements are incorrect.

**Comment by kloczek** [comment]
Other thing is that in case of that SuSe spec file seems is not used `python -m ipykernel install`.

**Comment by bnavigator** [comment]
> Other thing is that in case of that SuSe spec file seems is not used `python -m ipykernel install`.

Don't need to:
```
%files -n jupyter-ipykernel
%license COPYING.md
%{_jupyter_kernel_dir}/python3/
```

```
[ben@skylab:…thon-ipykernel]% rpm -ql binaries/jupyter-ipykernel-6.0.0-33.1.noarch.rpm
/usr/share/jupyter/kernels/python3
/usr/share/jupyter/kernels/python3/kernel.json
/usr/share/jupyter/kernels/python3/logo-32x32.png
/usr/share/jupyter/kernels/python3/logo-64x64.png
/usr/share/licenses/jupyter-ipykernel
/usr/share/licenses/jupyter-ipykernel/COPYING.md
```

**Comment by kloczek** [comment]
Still `debugpy` is required on pytest execution.
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILD/sphinxcontrib-towncrier-0.2.0a0/build/lib
+ PYTHONDONTWRITEBYTECODE=1
+ /usr/bin/pytest -ra --ignore ipykernel/debugger.py --ignore ipykernel/ipkernel.py --ignore ipykernel/kernelapp.py
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.11, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
benchmark: 3.4.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/tkloczko/rpmbuild/BUILD/ipykernel-6.0.0
plugins: forked-1.3.0, shutil-1.7.0, virtualenv-1.7.0, expect-1.1.0, httpbin-1.0.0, flake8-1.0.7, timeout-1.4.2, betamax-0.8.1, freezegun-0.4.2, case-1.5.3, isort-1.3.0, aspectlib-1.5.2, asyncio-0.15.1, toolbox-0.5, xprocess-0.17.1, aiohttp-0.3.0, checkdocs-2.7.0, mock-3.6.1, rerunfailures-9.1.1, requests-mock-1.9.3, cov-2.12.1, pyfakefs-4.5.0, cases-3.6.1, flaky-3.7.0, hypothesis-6.14.0, benchmark-3.4.1, xdist-2.3.0, pylama-7.7.1, datadir-1.3.1, regressions-2.2.0, Faker-8.9.0
collected 92 items / 3 errors / 89 selected

================================================================================== ERRORS ==================================================================================
________________________________________________________ ERROR collecting ipykernel/inprocess/tests/test_kernel.py _________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/ipykernel-6.0.0/ipykernel/inprocess/tests/test_kernel.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ipykernel/inprocess/tests/test_kernel.py:14: in <module>
    from ipykernel.inprocess.ipkernel import InProcessKernel
ipykernel/inprocess/ipkernel.py:13: in <module>
    from ipykernel.ipkernel import IPythonKernel
ipykernel/ipkernel.py:20: in <module>
    from .debugger import Debugger
ipykernel/debugger.py:14: in <module>
    import debugpy
E   ModuleNotFoundError: No module named 'debugpy'
_____________________________________________________________ ERROR collecting ipykernel/tests/test_connect.py _____________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/ipykernel-6.0.0/ipykernel/tests/test_connect.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ipykernel/tests/test_connect.py:18: in <module>
    from ipykernel.kernelapp import IPKernelApp
ipykernel/kernelapp.py:42: in <module>
    from .ipkernel import IPythonKernel
ipykernel/ipkernel.py:20: in <module>
    from .debugger import Debugger
ipykernel/debugger.py:14: in <module>
    import debugpy
E   ModuleNotFoundError: No module named 'debugpy'
___________________________________________________________ ERROR collecting ipykernel/tests/test_pickleutil.py ____________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/ipykernel-6.0.0/ipykernel/tests/test_pickleutil.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ipykernel/tests/test_pickleutil.py:4: in <module>
    from ipykernel.pickleutil import can, uncan, codeutil
ipykernel/pickleutil.py:21: in <module>
    from ipyparallel.serialize import codeutil
E   ModuleNotFoundError: No module named 'ipyparallel'
============================================================================= warnings summary =============================================================================
ipykernel/tests/test_pickleutil.py:4
  /home/tkloczko/rpmbuild/BUILD/ipykernel-6.0.0/ipykernel/tests/test_pickleutil.py:4: DeprecationWarning: ipykernel.pickleutil is deprecated. It has moved to ipyparallel.
    from ipykernel.pickleutil import can, uncan, codeutil

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================================= short test summary info ==========================================================================
ERROR ipykernel/inprocess/tests/test_kernel.py
ERROR ipykernel/tests/test_connect.py
ERROR ipykernel/tests/test_pickleutil.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================================================= 1 warning, 3 errors in 1.04s =======================================================================
```
BTW  .. please have look on that DeprecationWarning.

**Comment by bnavigator** [comment]
The fact that you are incapable of installing debugpy into your build and test environment is not ipykernel's fault. Stop spamming issue trackers.

**Comment by Carreau** [comment]
> It is about problems with packaging and using module which is not ready for even python 3.8 :(

Debugpy seem to be ready for python 3.8 afaict, and if I understand this thread correctly it is just not packaged for a few linux distribution. 

Therefore my understanding is that you want to make debugpy an optional dependency ? Is that a better interpretation of what you are asking ? We can't control and wait for all downstream to package all dependencies on all python version to start using them, though we can try to make efforts. 

I'm not going to guarantee we'll do it, but we we can at least keep track of the progress. 

What about renaming the issue to "Attempt to make debugpy optional to simplify linux packaging" ?
We'll probably not do it for 6.0.1 but likely can do it for the next minor release, like 6.1 maybe.

--- 

Also side note, please try to keep the conversation civil, I think there is just a language barrier/ translation/incomprehension. And that no-one is trying to spam or be aggressive.

**Comment by kloczek** [comment]
> I agree with @bnavigator that @kloczek has some issues when installing debugpy in their build env and that has nothing to do with an ipykernel bug (hence this issue should be closed).
> 
> @kloczek, as you can see [here](https://github.com/ipython/ipykernel/runs/2964241599), for instance, ipykernel is being tested on Python 3.7 to 3.9 without problems.

OK maybe it is not obvious but I'm only poinyting on simple fact that new version ipykernel module started using other module which has some serious issues.
Issue on which I've pointed has nothing to do with ipykernel testing or my build env but with fact that `debugpy` code uses python 2.x syntax and that module is now used by new ipykernel version.
Only this and nothing more.

**Comment by bnavigator** [comment]
@kloczek:
> OK maybe it is not obvious but I'm only poinyting on simple fact that new version ipykernel module started using other module which has some serious issues.

That is your opinion but nobody confirmed it. To the contrary, you have been pointed to the fact that there are working wheels for debugpy on PyPI and conda. For current Python 3 versions. And even that building rpm packages, which is obviously your intention, is possible.

> Issue on which I've pointed has nothing to do with ipykernel testing or my build env 

Yes it does. The title of this issue is "`python -m ipykernel install` fails on missing `debugpy`". Because you failed to install debugpy despite it being correctly declared as dependency.

> but with fact that `debugpy` code uses python 2.x syntax and that module is now used by new ipykernel version.

No it doesn't. You have been told in one of your numerous opened issues: https://github.com/microsoft/debugpy/issues/652#issuecomment-872448473 pointing to https://github.com/fabioz/PyDev.Debugger/issues/141

**Comment by Carreau** [comment]
> OK maybe it is not obvious but I'm only poinyting on simple fact that new version ipykernel module started using other module which has some serious issues.
> Issue on which I've pointed has nothing to do with ipykernel testing or my build env but with fact that `debugpy` code uses python 2.x syntax and that module is now used by new ipykernel version.


Well using new dependencies is our rights, we are the developers of the libraries, and we now have dependencies on `debugpy`, `importlib-metadata<4` for python version lower than 3.8 and `matplotlib-inline`. These new dependencies are one of the reasons we bumped the version number to 6.0.0, it is a major incompatible new version.

Debugpy work on 3.8

```
$ python
Python 3.8.5 | packaged by conda-forge | (default, Sep 16 2020, 17:43:11)
[Clang 10.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import debugpy
```

You seem to be the only one that find debugpy has some "serious issues", from what I can tell this is because you are trying to byte-compile ahead of time files that you should not. Then, exclude those files.

If you want to request that we make debugpy an optional dependency, please open another issue. As far what it requested in this bug report, this is a non-issue and work as expected.
