### ISSUE TITLE
Weird output after upgrading to ipykernel6

### ISSUE THREAD

**Issue by DonJayamanne** [ipython/ipykernel#729]
Thanks for this awesome package.

Updated to the latest ipykernel6 and started seeing some weird output when using `sys.stdout.write` (without flushing it).

Steps to repro:
* Install latest ipykernel & IPython, and we get some weird results.
* Below is from Jupyter notebooks.

<img width="347" alt="Screen Shot 2021-07-14 at 13 01 23" src="https://user-images.githubusercontent.com/1948812/125685348-4dc77b1b-6719-4eae-8c96-de5a84f4ceb9.png">

**Comment by DonJayamanne** [comment]
Seems to be printing the total number of characters in the stdout stream buffer.
E.g. if i change it to `sys.stdout.write("abc")`, then i get  `3`

**Comment by agoose77** [comment]
Is this not to be expected? IO `write` calls return the number of characters written, and in this case the result is displayed because the expression is the final expression in the cell.

**Comment by DonJayamanne** [comment]
Oh yes, that makes sense, for some reason I couldn't see this in the older versions hence assumed it was a bug.
Yes you are right, this is expected. Thanks
