### ISSUE TITLE
Get rid of nose, and ref to IPython.testing.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipykernel#744]
For next major of IPython I'm going to try to nuke everything related to nose, that include a lot of thing in `IPython.testing`.

I suggest IPykernel try to do the same as nose has been unmaintained for quite some time, and that any reference to IPython.testing be check to see if it can be replaced.

**Comment by Kojoley** [comment]
I think this could be closed now. `IPython.testing` is no longer used by ipykernel and the last nose imports are optional (IPython compatibility thing). The #397 is no longer relevant too.

**Comment by Carreau** [comment]
Yep, thanks, let's close.
