### ISSUE TITLE
IPykernel is broken with IPython 7.27.0+

### ISSUE THREAD

**Issue by ccordoba12** [ipython/ipykernel#755]
That release removed its dependency on `ipython_genutils`, but IPykernel is still using it in several places. Since it was not declared directly in `setup.py`, the package is broken when installed in a clean env.

@Carreau, could you take a look at this one?

**Comment by Carreau** [comment]
yes, I'll have a look.

**Comment by ccordoba12** [comment]
Thanks!

**Comment by Carreau** [comment]
it's probably also due to the latest traitlets release that remove the dependency on `ipython_genutils` as well.

**Comment by Carreau** [comment]
new patch version should be released on PyPI and conda-forge, let us know if all is ok.

**Comment by ccordoba12** [comment]
Thanks @Carreau for your prompt response and @blink1073 for the new release. I can confirm IPykernel is working fine now.
