### ISSUE TITLE
Call to process_one(wait=False) raises exception when there is nothing to process

### ISSUE THREAD

**Issue by Kirill888** [ipython/ipykernel#763]
I think code here is trying to catch wrong exception:

https://github.com/ipython/ipykernel/blob/3c6037fbed4431a6997414918bfc6a65b13070e7/ipykernel/kernelbase.py#L442-L445

My guess is that `tornado.queues.QueueEmpty` was the intended exception, and not `asyncio.QueueEmpty`

**Comment by blink1073** [comment]
Fixed in #817
