### ISSUE TITLE
f-strings autocomplete incorrectly

### ISSUE THREAD

**Issue by psarka** [ipython/ipykernel#785]
When typing an f-string in the jupyter lab notebook with ipykernel 6.0.1 the autocompletion of the `'` or `"` character does work as expected.

In particular this is a sequence of characters one gets when typing (verical dash `|` marks the cursor position):

```python
x=f|
x=f'|
x=f'{|
x=f'{h|
x=f'{hi|
x=f'{hi}|
x=f'{hi}'|'
```

As a result, the user always has to delete the thrid `'` or `"` character.

**Comment by psarka** [comment]
In case I filed this in the wrong repo, please let me know, I'll open it elsewhere :)

(If you just don't have time, then all good, I don't mean to bother)

**Comment by blink1073** [comment]
Hi @psarka, the autocompletion is handled in `ipython`, I'll move the issue.

**Comment by blink1073** [comment]
@meeseeksdev please migrate to ipython/ipython
