### ISSUE TITLE
BUG: Multiple incompatible subclass instances of ZMQInteractiveShell are being created

### ISSUE THREAD

**Issue by jakirkham** [ipython/ipykernel#79]
I think this is an `ipykernel` bug, but maybe it is an `ipython` bug. Sorry if I got the wrong repo. I tried to reproduce this issue ( https://github.com/ipython/ipython/issues/7122 ). However, I got this other unrelated issue instead.

Environment details are as follows.

    $ conda list
    # packages in environment at /zopt/conda/envs/ipy:
    #
    appnope                   0.1.0                    py27_0    defaults
    decorator                 4.0.4                    py27_0    defaults
    ipykernel                 4.1.1                    py27_0    defaults
    ipython                   4.0.0                    py27_1    defaults
    ipython-genutils          0.1.0                     <pip>
    ipython_genutils          0.1.0                    py27_0    defaults
    jupyter-client            4.1.1                     <pip>
    jupyter-core              4.0.6                     <pip>
    jupyter_client            4.1.1                    py27_0    defaults
    jupyter_core              4.0.6                    py27_0    defaults
    numpy                     1.10.1                   py27_0    defaults
    openssl                   1.0.2d                        0    defaults
    path.py                   8.1.2                    py27_0    defaults
    pexpect                   3.3                      py27_0    defaults
    pickleshare               0.5                      py27_0    defaults
    pip                       7.1.2                    py27_0    defaults
    python                    2.7.10                        2    defaults
    python.app                1.2                      py27_4    defaults
    pyzmq                     14.7.0                   py27_1    defaults
    readline                  6.2                           2    <unknown>
    setuptools                18.4                     py27_0    defaults
    simplegeneric             0.8.1                    py27_0    defaults
    sqlite                    3.8.4.1                       1    <unknown>
    tk                        8.5.18                        0    <unknown>
    traitlets                 4.0.0                    py27_0    defaults
    wheel                     0.26.0                   py27_1    defaults
    zeromq                    4.1.3                         0    defaults
    zlib                      1.2.8                         0    <unknown>

Code to reproduce.

    $ ipython
    Python 2.7.10 |Continuum Analytics, Inc.| (default, Oct 19 2015, 18:31:17) 
    Type "copyright", "credits" or "license" for more information.
    
    IPython 4.0.0 -- An enhanced Interactive Python.
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.
    
    In [1]: from IPython.kernel.zmq.datapub import publish_data
    /zopt/conda/envs/ipy/lib/python2.7/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
      "You should import from ipykernel or jupyter_client instead.", ShimWarning)
    
    In [2]: import numpy as np
    
    In [3]: myarr = np.ones(2 * 1024 * 1024 * 1024 * 8 // 64) # 2 GB
    
    In [4]: publish_data({'x': myarr})
    ---------------------------------------------------------------------------
    MultipleInstanceError                     Traceback (most recent call last)
    <ipython-input-4-49f20562eb3f> in <module>()
    ----> 1 publish_data({'x': myarr})
    
    /zopt/conda/envs/ipy/lib/python2.7/site-packages/ipykernel/datapub.pyc in publish_data(data)
         55     """
         56     from ipykernel.zmqshell import ZMQInteractiveShell
    ---> 57     ZMQInteractiveShell.instance().data_pub.publish_data(data)
    
    /zopt/conda/envs/ipy/lib/python2.7/site-packages/traitlets/config/configurable.pyc in instance(cls, *args, **kwargs)
        389             raise MultipleInstanceError(
        390                 'Multiple incompatible subclass instances of '
    --> 391                 '%s are being created.' % cls.__name__
        392             )
        393 
    
    MultipleInstanceError: Multiple incompatible subclass instances of ZMQInteractiveShell are being created.

**Comment by minrk** [comment]
The multiple-instance error is because of something amiss with the shim. If you import from `ipykernel.datapub` it should work.

**Comment by jakirkham** [comment]
Tried that same error. See below for example.

    $ ipython
    Python 2.7.10 |Continuum Analytics, Inc.| (default, Oct 19 2015, 18:31:17) 
    Type "copyright", "credits" or "license" for more information.
    
    IPython 4.0.0 -- An enhanced Interactive Python.
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.
    
    In [1]: from ipykernel.datapub import publish_data
    
    In [2]: import numpy as np
    
    In [3]: myarr = np.ones(2 * 1024 * 1024 * 1024 * 8 // 64)
    
    In [4]: publish_data({'x': myarr})
    ---------------------------------------------------------------------------
    MultipleInstanceError                     Traceback (most recent call last)
    <ipython-input-4-49f20562eb3f> in <module>()
    ----> 1 publish_data({'x': myarr})
    
    /zopt/conda/envs/nanshenv/lib/python2.7/site-packages/ipykernel/datapub.pyc in publish_data(data)
         55     """
         56     from ipykernel.zmqshell import ZMQInteractiveShell
    ---> 57     ZMQInteractiveShell.instance().data_pub.publish_data(data)
    
    /zopt/conda/envs/nanshenv/lib/python2.7/site-packages/traitlets/config/configurable.pyc in instance(cls, *args, **kwargs)
        389             raise MultipleInstanceError(
        390                 'Multiple incompatible subclass instances of '
    --> 391                 '%s are being created.' % cls.__name__
        392             )
        393 
    
    MultipleInstanceError: Multiple incompatible subclass instances of ZMQInteractiveShell are being created.

**Comment by minrk** [comment]
Oh, I didn't notice that you were using regular terminal IPython. Terminal IPython doesn't have data publication, so the bug is actually that it should raise an AttributeError or NotImplementedError or some such. Make sure you are using an IPython kernel, such as `jupyter console`, notebook, or qtconsole.

**Comment by jakirkham** [comment]
There's a `jupyter console`?! Cool! I did not even know this existed. How does it determine what kernel to use?

**Comment by jakirkham** [comment]
So, I tried the same exercise with `jupyter_console` version `4.0.3`. Here's what happened.

    $ jupyter console
    Jupyter Console 4.0.3
    
    [ZMQTerminalIPythonApp] Loading IPython extension: storemagic
    [ZMQTerminalIPythonApp] Loading IPython extension: h5py.ipy_completer
    
    In [1]: from ipykernel.datapub import publish_data
    
    In [2]: import numpy as np
    
    In [3]: myarr = np.ones(2 * 1024 * 1024 * 1024 * 8 // 64)
    
    In [4]: publish_data({'x': myarr})
    Traceback (most recent call last):
      File "/zopt/conda/envs/nanshenv/bin/jupyter-console", line 5, in <module>
        app.main()
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
        return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/traitlets/config/application.py", line 592, in launch_instance
        app.start()
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/jupyter_console/app.py", line 155, in start
        super(ZMQTerminalIPythonApp, self).start()
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 353, in start
        self.shell.mainloop()
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/jupyter_console/interactiveshell.py", line 420, in mainloop
        self.interact(display_banner=display_banner)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/jupyter_console/interactiveshell.py", line 588, in interact
        self.run_cell(source_raw)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/jupyter_console/interactiveshell.py", line 174, in run_cell
        self.handle_iopub(msg_id)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/jupyter_console/interactiveshell.py", line 262, in handle_iopub
        sub_msg = self.client.iopub_channel.get_msg()
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/jupyter_client/blocking/channels.py", line 55, in get_msg
        return self._recv()
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/jupyter_client/blocking/channels.py", line 41, in _recv
        msg = self.socket.recv_multipart(**kwargs)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/zmq/sugar/socket.py", line 361, in recv_multipart
        part = self.recv(flags, copy=copy, track=track)
      File "zmq/backend/cython/socket.pyx", line 676, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:6507)
      File "zmq/backend/cython/socket.pyx", line 710, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:6307)
      File "zmq/backend/cython/socket.pyx", line 147, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:1877)
      File "zmq/backend/cython/checkrc.pxd", line 19, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:6920)
        raise Again(errno)
    Again: Resource temporarily unavailable
    
    If you suspect this is an IPython bug, please report it at:
        https://github.com/ipython/ipython/issues
    or send an email to the mailing list at ipython-dev@scipy.org
    
    You can print a more detailed traceback right now with "%tb", or use "%debug"
    to interactively debug it.
    
    Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
        %config Application.verbose_crash=True

**Comment by takluyver** [comment]
Closing because that function is being moved to ipyparallel in any case.

**Comment by jakirkham** [comment]
So, should this issue be moved somewhere else? AFAICT this is still not fixed.

**Comment by takluyver** [comment]
It sounds like the fix is just to make the error message clearer. If there's still anything to do, ipyparallel is the relevant repo:
https://github.com/ipython/ipyparallel

**Comment by jakirkham** [comment]
Sorry, its been awhile since I look at this. I was wrong. There was a bug. It was a bug in zeromq. @minrk added a workaround for pyzmq. ( https://github.com/zeromq/pyzmq/pull/782 ) So, this is actually fixed.
