### ISSUE TITLE
ipykernel complains it can not log me out of linkedin (program has nothing to do with linkedin)

### ISSUE THREAD

**Issue by Thomas-Walker-Lynch** [ipython/ipykernel#797]
I am running a short program in a Jupyter Notebook.  It makes a connection on a local socket using 127.0.0.1 and a port number hard coded, then pulls messages and puts them in an output widget.  Yet, the program is currently issuing this error:

```
  File "/tmp/ipykernel_633114/3169154848.py", line 20
    https://www.linkedin.com/m/logout/
          ^
SyntaxError: invalid syntax
```
The program makes no external network connections.   It has nothing to do with linkedin.   The messages do not have anything to do with linkedin.  I really don't know where it is even getting this string. 

In the weird world of ipykernel, does this make any sense?

**Comment by blink1073** [comment]
Hi @Thomas-Walker-Lynch, I'm not aware of anything `ipykernel` or `ipython` itself that would cause the issue you're seeing.

**Comment by Thomas-Walker-Lynch** [comment]
There is nothing in any code running on this system that would access linkedin for log out. 
  ... "/tmp/ipykernel_633114/3169154848.py" ?   What is making those  files?  When I look in /tmp it is not there.

**Comment by afshin** [comment]
It's not obvious to me what has happened here, but it looks at though at some point while you were debugging the text of one of your cells included that URL -- which is not a valid line of Python -- so it caused execution to stall. Is it possible that an errant copy & paste operation ended up inserting that URL string into one of your code cells?

**Comment by Thomas-Walker-Lynch** [comment]
Thanks afshin, blink1073.  There seems to be a file corruption issue, so the notebook was foobar.   It was confusing to see data that had not been typed, and errors pointing into the kernel temp files with no error from the actual corrupted source.   and why a linkedin logout URL in the error of all things ...

**Comment by blink1073** [comment]
The temp files are generated by the debugger.  Haha agreed it was funny that it was LinkedIn of all things.

**Comment by Thomas-Walker-Lynch** [comment]
Upon logging out of linkedin, that URL flashes by as it redirects back to the sign-in page. I  tried logging out a few times and only saw it once, usually it does not even show in the navigation panel.  Hitting back after logging out goes to a different URL.  The URL snagged by copying the sign-out button is different.  

Hence, that string is unlikely to have come from a manual action of placing it in the cut buffer.  It is probable that while a notebook was open I used the same browser to visit linkedin.  It seems more likely that somehow there was communication between them.  Does a logout trigger an event?

After the error the debugger button did not work.  Pushing it issued an error  saying that the kernel did not support debugging and that a different one would have to be used.  Given that the kernel 'did not support debugging'  that is a curious thing that the temp files are generated by the debugger and the error cited one of those.   There was no such other kernel option on the kernel change menu.   So I shut everything down, copied, and edited, and started over.   You  guys probably know about this.  I will go look it up sometime.

SSD drives keep a log of errors, and can run self tests, these can be invoked with the program smartctl on linux.   The device in that machine looks healthy with  zero for the bad block count, and a short test found no errors.  However, I have been a bit suspicious of this device because there have been some very long delays, and a corrupted file turned up after an archive.

**Comment by afshin** [comment]
> It seems more likely that somehow there was communication between them. Does a logout trigger an event? Perhaps there is a function in Jupyter for grabbing the contents of the navigation panel?

I can categorically say: there is **no functionality** in any application or extension published by Jupyter that would or could connect any activity on a different site to its execution.

Perhaps another extension on your browser manipulates the contents of your web page (an ad blocker, a form filler, some other extension altogether) or perhaps some other sequences of events led to this.

Please feel free to-open this issue or file a new one if you encounter a reproducible error in `ipykernel`.
