### ISSUE TITLE
Where is the command handler located

### ISSUE THREAD

**Issue by jules-datascientest** [ipython/ipykernel#802]
Hi, quick question, and I think this is the correct repository.

I'm looking for the bit of code that handles the execution of `!xx` commands so I can block `!pip` on my company's custom jupyter.

Could you point it to me ? Thanks!

**Comment by blink1073** [comment]
Hi @jules-datascientest, it is provided by one of the magics in [`ipython`](https://github.com/ipython/ipython), though I'm not sure exactly where in the codebase.

**Comment by jules-datascientest** [comment]
Thanks @blink1073, I'll go look around and ask over there :) Cheers !
