### ISSUE TITLE
v6.6.0 broke debugging "step over" instruction at top level

### ISSUE THREAD

**Issue by kycutler** [ipython/ipykernel#832]
Since ipykernel>=6.6.0, using the "step over" instruction when debugging top-level code will step into IPython runtime code (see GIF below). This is confusing behavior and definitely not what most users will want or expect.

![stepoverbug](https://user-images.githubusercontent.com/67761731/148422647-d995c002-2477-4229-b569-cfc30a122a95.gif)

I believe this regression is due to #812. This also complicates the stack trace by including frames from IPython -- at best this clutters the interface, and at worst this could confuse users as to what code is running or where their code is.

**Comment by JohanMabille** [comment]
Indeed this regression is due to #812 . I'm trying to find a alternative so that we can break into the standard library without changing the step over behavior, otherwise we will have to filter stop events.
