### ISSUE TITLE
`/1` yields `'int' object is not callable`

### ISSUE THREAD

**Issue by OverLordGoldDragon** [ipython/ipykernel#846]
`/1`
```python
<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
C:\Users\OverL\AppData\Local\Temp/ipykernel_27764/875669085.py:1: SyntaxWarning: 'int' object is not callable; 
perhaps you missed a comma?
  1()
Traceback (most recent call last):

  File "C:\Users\OverL\AppData\Local\Temp/ipykernel_27764/875669085.py", line 1, in <module>
    1()

TypeError: 'int' object is not callable
```
Plain terminal yields
```python
  File "<stdin>", line 1
    /1
    ^
SyntaxError: invalid syntax
```
which looks cleaner, and doesn't accuse of what hasn't happened (calling `1`).

**Comment by Carreau** [comment]
You just discovered the autocall/autoparens feature of IPython. 

https://ipython.readthedocs.io/en/stable/interactive/magics.html?highlight=autocall#magic-autocall

Terminal IPython say the same.

**Comment by OverLordGoldDragon** [comment]
>Terminal IPython say the same

Not for me

![image](https://user-images.githubusercontent.com/16495490/158015056-5965603e-66a6-4f37-9166-bff01ad5be86.png)

**Comment by Carreau** [comment]
ipython  != python

**Comment by OverLordGoldDragon** [comment]
Interesting, thanks.
