### ISSUE TITLE
How to embed IPython.core.interactiveshell.InteractiveShell silently?

### ISSUE THREAD

**Issue by ooblahman** [ipython/ipykernel#90]
I'm writing a server application that evaluates code strings it receives in certain namespaces, depending on the context. I'm trying to use the IPython-provided ```InteractiveShell``` class to run the user code. Couple of questions:

1) What's the correct way to instantiate the shell, provide an initial namespace, and run code in it? The API as specified [here](http://ipython.readthedocs.org/en/stable/api/generated/IPython.core.interactiveshell.html#IPython.core.interactiveshell.ExecutionResult) doesn't say how to instantiate the shell in an embedded app (i.e. in a way that doesn't take over the app by blocking execution and providing an input prompt, but silently as an object I can pass code to). 
2) Meta-question: What I want is essentially an ```InteractiveConsole```, with autocompletion and magics enabled. Is InteractiveShell the right class to be using, or is there a lower-level class that would be better suited? I'm not conforming to IPython's messaging protocol or ZMQ topology, so it doesn't make sense to subclass the ```KernelBase``` class or write a wrapper kernel around ```ipykernel```.

**Comment by takluyver** [comment]
> 1) What's the correct way to instantiate the shell, provide an initial namespace, and run code in it? The API as specified here doesn't say how to instantiate the shell in an embedded app (i.e. in a way that doesn't take over the app by blocking execution and providing an input prompt, but silently as an object I can pass code to). 

How are you doing that? Just instantiating InteractiveShell should not make anything prompt for input.

`InteractiveShell` is the core API class, which has methods and attributes to deal with things like executing code, calculating tab completions, etc. Based on your description, it sounds like this is what you want. You can pass the parameter `user_ns` to give it a custom namespace.

Then there are two subclasses of InteractiveShell: `TerminalInteractiveShell`, which runs the readline based interface of IPython in the terminal, and `ZMQInteractiveShell`, which is used by the kernel machinery to expose the InteractiveShell stuff as a network service.

**Comment by ooblahman** [comment]
Oh, instantiating InteractiveShell in the interpreter takes over the interpreter, but somehow putting it in a program and running does not... 
<http://puu.sh/m9Msd/82273a73e8.png>

**Comment by ooblahman** [comment]
Oh, instantiating InteractiveShell in the interpreter takes over the interpreter, but somehow putting it in a program and running does not... 
<http://puu.sh/m9Msd/82273a73e8.png>

**Comment by takluyver** [comment]
Aha. I would guess that it's not actually running an ipython shell, but
something is setting sys.ps1, which defines the prompt in the plain Python
shell. We probably needn't do that, but it's also likely harmless for your
use case.
