### ISSUE TITLE
Thread to monitor the kernel usage (CPU, Memory...)

### ISSUE THREAD

**Issue by echarles** [ipython/ipykernel#912]
While implementing a jupyterlab extension to monitor the kernel usage (https://github.com/Quansight/jupyterlab-kernel-usage), a few PRs have been merged to use [psutil](https://psutil.readthedocs.io/en/latest) to return Memory, CPU usage of the machine and the kernel processes.

- https://github.com/ipython/ipykernel/pull/805
- https://github.com/ipython/ipykernel/pull/865
- https://github.com/ipython/ipykernel/pull/908

This has worked great for most of the metrics, but we hit now an issue for the kernel CPU reported on https://github.com/Quansight/jupyterlab-kernel-usage/issues/11. psutil returns the CPU based on the last call, so it looks like everytime we ask the CPU via the kernel websocket, it return zero as psutil considers it is the first time the request is made, see info on:

- https://psutil.readthedocs.io/en/latest/#psutil.cpu_percent
- https://stackoverflow.com/questions/24367424/cpu-percentinterval-none-always-returns-0-regardless-of-interval-value-python/27229967#27229967

Please note that similar issue is reported on the jupyter-resource-usage extension (which monitors the server usage, not the kernel usage) https://github.com/jupyter-server/jupyter-resource-usage/issues/107

A solution would be to maintain a separated thread that would be responsible to return that CPU in a correct way based on psutil. 

What would be the impact to create such as separated thread? What are the already existing threads? Does it sound like a reasonable approach? Any other idea?

**Comment by blink1073** [comment]
> What are the already existing threads? 

It looks like the existing threads are heartbeat, iopub, and control.

Jupyter Client has threads for iopub, shell, stdin, control, and heartbeat.

I think it is worth trying to add a another thread, but maybe this is a good opportunity to add a performance regression check.  SciPy uses [airspeed velocity](https://github.com/scipy/scipy/blob/8a64c938ddf1ae4c02a08d2c5e38daeb8d061d38/doc/source/dev/contributor/benchmarking.rst#benchmarking-scipy-with-airspeed-velocity).

**Comment by echarles** [comment]
> It looks like the existing threads are heartbeat, iopub, and control.

Thx @blink1073 Great to know ipykernel is already kind with kernel hosting. I guess an additional one `monitor`, or maybe `telemetry` (thinking about the discussion in jupyter-server https://github.com/jupyter-server/jupyter_server/issues/780 - maybe offtopic here, not sure?) could be added.

> Jupyter Client has threads for iopub, shell, stdin, control, and heartbeat.

if we add a thread in ipykernel to monitor the resources, does that imply we ned also a thread in `jupyter-client`. My first intake was no, but I may miss context.

> I think it is worth trying to add a another thread,

+1

> but maybe this is a good opportunity to add a performance regression check. SciPy uses [airspeed velocity](https://github.com/scipy/scipy/blob/8a64c938ddf1ae4c02a08d2c5e38daeb8d061d38/doc/source/dev/contributor/benchmarking.rst#benchmarking-scipy-with-airspeed-velocity).

It would be good. I guess that is not a small task to get that performance benchmarking setup.

**Comment by blink1073** [comment]
> does that imply we need also a thread in jupyter-client

I don't believe so, since client is launching ipykernel in a subprocess

> I guess that is not a small task to get that performance benchmarking setup.

I don't think it needs to be too comprehensive to start.

**Comment by dimpase** [comment]
Adding `psutil` as a dependency makes it impossible to install `ipython` on Cygwin. (`psutil` refused to merge  @embray's patch for Cygwin in https://github.com/embray/psutil).

**Comment by dimpase** [comment]
@mkoeppe
