### ISSUE TITLE
No module named 'IPython.qt'

### ISSUE THREAD

**Issue by andia89** [ipython/ipykernel#914]
WHen trying to open a qtconsole in jupyter notebook

in this line 

https://github.com/ipython/ipykernel/blob/51a613d501a86073ea1cdbd8023a168646644c6a/ipykernel/connect.py#L109

the command 

    cmd = ";".join(["from IPython.qt.console import qtconsoleapp", "qtconsoleapp.main()"])

is spawned. However on my machine this results in the error in the header. For me to make it work I have to change that to 

   cmd = ";".join(["from qtconsole import qtconsoleapp", "qtconsoleapp.main()"])

then everything is working the way it should. It seems this is the more uptodate way to spawn an jupyter-console

**Comment by blink1073** [comment]
Nice catch!  Would you like to submit a PR?

**Comment by andia89** [comment]
done
