### ISSUE TITLE
Allow serving kernel with UnixSockets?

### ISSUE THREAD

**Issue by arogozhnikov** [ipython/ipykernel#925]
As I understand, ipykernel_launcher can only accept ports but not unix sockets when started. 

For pyzmq unix domain sockets are a valid transport, so how about supporting them too?

Main advantages I see:
- ability to easily and safely expose kernels from a docker
- allow easy listing of kernels with third-party conventions about channels 
    - case when kernel is started on a remote machine, then either disconnect happens or server process restarted. If specific naming convention followed, process can pick up existing kernel instead of creating a new one

Additional advantages:
- most of server-kernel communication happens within the same machine, so it should get slightly faster
- fewer port allocations
- safety? Not sure

**Comment by minrk** [comment]
unix domain sockets are already supported. You can instruct kernels to use them with `c.KernelManager.transport = 'ipc'` in your `jupyter_server_config.py` (or `jupyter_notebook_config.py` if you're using the legacy notebook server). With that, all sockets should use zmq's ipc transport.

**Comment by arogozhnikov** [comment]
@minrk thank you for pointing! 

For posterity:

I did not understand how correct connection file should look like, so here is the answer:

```
{
  "shell_port": 1,
  "iopub_port": 2,
  "stdin_port": 3,
  "control_port": 4,
  "hb_port": 5,
  "ip": "/Users/<username>/Library/Jupyter/runtime/kernel-d702b3e8-48fb-421c-abcd-b22a1bf87405-ipc",
  "key": "dbcdd995-2ba15a756fc4e252f7beabcd",
  "transport": "ipc",
  "signature_scheme": "hmac-sha256",
  "kernel_name": ""
}
```
and it will create sockets for communication:
```
/Users/<username>/Library/Jupyter/runtime/kernel-d702b3e8-48fb-421c-abcd-b22a1bf87405-ipc-1
/Users/<username>/Library/Jupyter/runtime/kernel-d702b3e8-48fb-421c-abcd-b22a1bf87405-ipc-2
/Users/<username>/Library/Jupyter/runtime/kernel-d702b3e8-48fb-421c-abcd-b22a1bf87405-ipc-3
/Users/<username>/Library/Jupyter/runtime/kernel-d702b3e8-48fb-421c-abcd-b22a1bf87405-ipc-4
/Users/<username>/Library/Jupyter/runtime/kernel-d702b3e8-48fb-421c-abcd-b22a1bf87405-ipc-5
```
